## Reading the existing processed file for each dataset

In [1]:
import os
import copy
import sys
import argparse
import asyncio
from tqdm import tqdm
import random
from pprint import pprint
from dotenv import load_dotenv
from collections import defaultdict

# Ensure repository root is on sys.path so "Code" is importable when run directly
REPO_ROOT = '/dartfs-hpc/rc/home/j/f006f3j/lab/omar/LoQA'
if REPO_ROOT not in sys.path:
    sys.path.insert(0, REPO_ROOT)
# Load environment variables from .env file
load_dotenv(os.path.join(REPO_ROOT, ".env"))

from Code.src.utils.io import read_json_file, save_json_file
from Code.src.utils.qg_and_pd_utils import read_data_split

/dartfs-hpc/rc/home/j/f006f3j/lab/omar/conda/loqaGpu/lib/python3.10/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [7]:
import os
import json
import random


def is_valid_sample(sample):
    """Check if a sample is valid (has non-null, non-empty raw-initial-ground-truth)."""
    arg_value = sample.get("raw-initial-ground-truth", None)
    if arg_value is None:
        return False
    if isinstance(arg_value, (list, str)) and len(arg_value) == 0:
        return False
    if isinstance(arg_value, list) and len(arg_value) == 1 and arg_value[0] == "null":
        return False
    return True


def filter_valid_samples(samples):
    """Filter out invalid samples (where raw-initial-ground-truth is None, empty, or "null")."""
    return [sample for sample in samples if is_valid_sample(sample)]


def load_all_splits_from_processed(dataset_root: str, dataset_name: str):
    """Load all samples from train/dev/test splits in the *-processed.json file."""
    processed_path = os.path.join(dataset_root, dataset_name, f"{dataset_name}-all.json")
    data = read_json_file(processed_path)

    all_samples = []
    for split_name in ["train", "dev", "test"]:
        if split_name in data:
            all_samples.extend(data[split_name])
    return all_samples


def dedup_by_context_role_gt(samples):
    """Ensure no duplicate (context, role, raw-initial-ground-truth) appears more than once."""
    seen = set()
    unique = []
    for s in samples:
        ctx = s.get("context")
        role = s.get("role")
        gt = tuple(s.get("raw-initial-ground-truth") or [])
        key = (ctx, role, gt)
        if key in seen:
            continue
        seen.add(key)
        unique.append(s)
    return unique


def split_samples_for_dataset(dataset_name: str, samples):
    """Shuffle and split into train/dev/test with dataset-specific counts."""
    # CaseReportBench: dev=350, test=350; others: dev=500, test=500
    if dataset_name == "CaseReportBench":
        test_count = 350
        dev_count = 350
    else:
        test_count = 500
        dev_count = 500

    random.shuffle(samples)
    n = len(samples)
    if n < test_count + dev_count:
        raise ValueError(
            f"Not enough valid samples for {dataset_name}: "
            f"have {n}, need at least {test_count + dev_count} for test+dev."
        )

    test_split = samples[:test_count]
    dev_split = samples[test_count:test_count + dev_count]
    train_split = samples[test_count + dev_count:]
    return {"train": train_split, "dev": dev_split, "test": test_split}


def create_final_splits_for_dataset(dataset_root: str, dataset_name: str, seed: int = 42):
    """High-level helper to create and save final train/dev/test splits."""
    random.seed(seed)

    # 1) Load all splits from processed
    all_samples = load_all_splits_from_processed(dataset_root, dataset_name)

    # 2) Filter valid samples
    valid_samples = filter_valid_samples(all_samples)

    # 3) Deduplicate by (context, role, raw-initial-ground-truth)
    unique_samples = dedup_by_context_role_gt(valid_samples)

    print(
        f"{dataset_name}: {len(all_samples)} total, "
        f"{len(valid_samples)} valid, {len(unique_samples)} unique (by context, role, GT)."
    )

    # 4) Split into train/dev/test with requested counts
    splits = split_samples_for_dataset(dataset_name, unique_samples)
    for split_name, split_samples in splits.items():
        print(f"{split_name}: {len(split_samples)} samples")

    # 5) Save each split to its own file and assign serial-numbers
    for split_name, split_samples in splits.items():
        # Reassign serial-number as split_name-idx (1-based)
        for idx, sample in enumerate(split_samples, start=1):
            sample["serial-number"] = f"{split_name}-{idx}"

        out_path = os.path.join(dataset_root, dataset_name, f"{dataset_name}-{split_name}.json")
        save_json_file(split_samples, out_path)
        print(f"Saved {split_name} split ({len(split_samples)} samples) to {out_path}")

    return splits

dataset_root = '/dartfs-hpc/rc/home/j/f006f3j/lab/omar/LoQA/Dataset'
dataset_names = ["DiscourseEE", "PHEE", "CaseReportBench", "MACCROBAT"]
seed = 42
for dataset_name in dataset_names:
    print(f"{'='*60}")
    print(f"Creating final splits for {dataset_name}")
    create_final_splits_for_dataset(dataset_root, dataset_name, seed)

============================================================
Creating final splits for DiscourseEE
Reading JSON file from: /dartfs-hpc/rc/home/j/f006f3j/lab/omar/LoQA/Dataset/DiscourseEE/DiscourseEE-all.json
DiscourseEE: 7446 total, 3354 valid, 3222 unique (by context, role, GT).
train: 2222 samples
dev: 500 samples
test: 500 samples
Data saved to: /dartfs-hpc/rc/home/j/f006f3j/lab/omar/LoQA/Dataset/DiscourseEE/DiscourseEE-train.json
Saved train split (2222 samples) to /dartfs-hpc/rc/home/j/f006f3j/lab/omar/LoQA/Dataset/DiscourseEE/DiscourseEE-train.json
Data saved to: /dartfs-hpc/rc/home/j/f006f3j/lab/omar/LoQA/Dataset/DiscourseEE/DiscourseEE-dev.json
Saved dev split (500 samples) to /dartfs-hpc/rc/home/j/f006f3j/lab/omar/LoQA/Dataset/DiscourseEE/DiscourseEE-dev.json
Data saved to: /dartfs-hpc/rc/home/j/f006f3j/lab/omar/LoQA/Dataset/DiscourseEE/DiscourseEE-test.json
Saved test split (500 samples) to /dartfs-hpc/rc/home/j/f006f3j/lab/omar/LoQA/Dataset/DiscourseEE/DiscourseEE-test.json
============================================================
Creating final splits for PHEE
Reading JSON file from: /dartfs-hpc/rc/home/j/f006f3j/lab/omar/LoQA/Dataset/PHEE/PHEE-all.json
PHEE: 72405 total, 22279 valid, 22274 unique (by context, role, GT).
train: 21274 samples
dev: 500 samples
test: 500 samples
Data saved to: /dartfs-hpc/rc/home/j/f006f3j/lab/omar/LoQA/Dataset/PHEE/PHEE-train.json
Saved train split (21274 samples) to /dartfs-hpc/rc/home/j/f006f3j/lab/omar/LoQA/Dataset/PHEE/PHEE-train.json
Data saved to: /dartfs-hpc/rc/home/j/f006f3j/lab/omar/LoQA/Dataset/PHEE/PHEE-dev.json
Saved dev split (500 samples) to /dartfs-hpc/rc/home/j/f006f3j/lab/omar/LoQA/Dataset/PHEE/PHEE-dev.json
Data saved to: /dartfs-hpc/rc/home/j/f006f3j/lab/omar/LoQA/Dataset/PHEE/PHEE-test.json
Saved test split (500 samples) to /dartfs-hpc/rc/home/j/f006f3j/lab/omar/LoQA/Dataset/PHEE/PHEE-test.json
============================================================
Creating final splits for CaseReportBench
Reading JSON file from: /dartfs-hpc/rc/home/j/f006f3j/lab/omar/LoQA/Dataset/CaseReportBench/CaseReportBench-all.json
CaseReportBench: 2484 total, 1320 valid, 1320 unique (by context, role, GT).
train: 620 samples
dev: 350 samples
test: 350 samples
Data saved to: /dartfs-hpc/rc/home/j/f006f3j/lab/omar/LoQA/Dataset/CaseReportBench/CaseReportBench-train.json
Saved train split (620 samples) to /dartfs-hpc/rc/home/j/f006f3j/lab/omar/LoQA/Dataset/CaseReportBench/CaseReportBench-train.json
Data saved to: /dartfs-hpc/rc/home/j/f006f3j/lab/omar/LoQA/Dataset/CaseReportBench/CaseReportBench-dev.json
Saved dev split (350 samples) to /dartfs-hpc/rc/home/j/f006f3j/lab/omar/LoQA/Dataset/CaseReportBench/CaseReportBench-dev.json
Data saved to: /dartfs-hpc/rc/home/j/f006f3j/lab/omar/LoQA/Dataset/CaseReportBench/CaseReportBench-test.json
Saved test split (350 samples) to /dartfs-hpc/rc/home/j/f006f3j/lab/omar/LoQA/Dataset/CaseReportBench/CaseReportBench-test.json
============================================================
Creating final splits for MACCROBAT
Reading JSON file from: /dartfs-hpc/rc/home/j/f006f3j/lab/omar/LoQA/Dataset/MACCROBAT/MACCROBAT-all.json
MACCROBAT: 6920 total, 6920 valid, 6882 unique (by context, role, GT).
train: 5882 samples
dev: 500 samples
test: 500 samples
Data saved to: /dartfs-hpc/rc/home/j/f006f3j/lab/omar/LoQA/Dataset/MACCROBAT/MACCROBAT-train.json
Saved train split (5882 samples) to /dartfs-hpc/rc/home/j/f006f3j/lab/omar/LoQA/Dataset/MACCROBAT/MACCROBAT-train.json
Data saved to: /dartfs-hpc/rc/home/j/f006f3j/lab/omar/LoQA/Dataset/MACCROBAT/MACCROBAT-dev.json
Saved dev split (500 samples) to /dartfs-hpc/rc/home/j/f006f3j/lab/omar/LoQA/Dataset/MACCROBAT/MACCROBAT-dev.json
Data saved to: /dartfs-hpc/rc/home/j/f006f3j/lab/omar/LoQA/Dataset/MACCROBAT/MACCROBAT-test.json
Saved test split (500 samples) to /dartfs-hpc/rc/home/j/f006f3j/lab/omar/LoQA/Dataset/MACCROBAT/MACCROBAT-test.json

In [10]:
for dataset_name in dataset_names:
    print(f"{'='*60}")
    print("Reading processed data for", dataset_name)
    for split_name in ["train", "dev", "test"]:
        file_path = os.path.join(dataset_root, dataset_name, f"{dataset_name}-{split_name}.json")
        if os.path.exists(file_path):
            print("Size of", split_name, "split:", len(read_json_file(file_path)))
        else:
            print(f"Warning: {file_path} not found. Skipping {split_name} split.")

============================================================
Reading processed data for DiscourseEE
Reading JSON file from: /dartfs-hpc/rc/home/j/f006f3j/lab/omar/LoQA/Dataset/DiscourseEE/DiscourseEE-train.json
Size of train split: 2222
Reading JSON file from: /dartfs-hpc/rc/home/j/f006f3j/lab/omar/LoQA/Dataset/DiscourseEE/DiscourseEE-dev.json
Size of dev split: 500
Reading JSON file from: /dartfs-hpc/rc/home/j/f006f3j/lab/omar/LoQA/Dataset/DiscourseEE/DiscourseEE-test.json
Size of test split: 500
============================================================
Reading processed data for PHEE
Reading JSON file from: /dartfs-hpc/rc/home/j/f006f3j/lab/omar/LoQA/Dataset/PHEE/PHEE-train.json
Size of train split: 21274
Reading JSON file from: /dartfs-hpc/rc/home/j/f006f3j/lab/omar/LoQA/Dataset/PHEE/PHEE-dev.json
Size of dev split: 500
Reading JSON file from: /dartfs-hpc/rc/home/j/f006f3j/lab/omar/LoQA/Dataset/PHEE/PHEE-test.json
Size of test split: 500
============================================================
Reading processed data for CaseReportBench
Reading JSON file from: /dartfs-hpc/rc/home/j/f006f3j/lab/omar/LoQA/Dataset/CaseReportBench/CaseReportBench-train.json
Size of train split: 620
Reading JSON file from: /dartfs-hpc/rc/home/j/f006f3j/lab/omar/LoQA/Dataset/CaseReportBench/CaseReportBench-dev.json
Size of dev split: 350
Reading JSON file from: /dartfs-hpc/rc/home/j/f006f3j/lab/omar/LoQA/Dataset/CaseReportBench/CaseReportBench-test.json
Size of test split: 350
============================================================
Reading processed data for MACCROBAT
Reading JSON file from: /dartfs-hpc/rc/home/j/f006f3j/lab/omar/LoQA/Dataset/MACCROBAT/MACCROBAT-train.json
Size of train split: 5882
Reading JSON file from: /dartfs-hpc/rc/home/j/f006f3j/lab/omar/LoQA/Dataset/MACCROBAT/MACCROBAT-dev.json
Size of dev split: 500
Reading JSON file from: /dartfs-hpc/rc/home/j/f006f3j/lab/omar/LoQA/Dataset/MACCROBAT/MACCROBAT-test.json
Size of test split: 500

## Statistics of the dataset

In [7]:
import numpy as np

dataset_root = '/dartfs-hpc/rc/home/j/f006f3j/lab/omar/LoQA/Dataset'
dataset_names = ["CaseReportBench", "PHEE", "DiscourseEE", "MACCROBAT"]
doc_id_keys = {
    "CaseReportBench": "pmcid",
    "PHEE": "id",
    "DiscourseEE": "doc_id",
    "MACCROBAT": "doc_id",
}

all_stats = {}

for dataset_name in dataset_names:
    samples = []
    for split_name in ["train", "dev", "test"]:
        file_path = os.path.join(dataset_root, dataset_name, f"{dataset_name}-{split_name}.json")
        if os.path.exists(file_path):
            samples.extend(read_json_file(file_path))

    # 1) Unique roles
    roles = set(s.get("role", "") for s in samples)

    # 2) Context length in words
    ctx_lengths = [len(s.get("context", "").split()) for s in samples]

    # 3) Argument counts (list length per sample)
    arg_counts = [len(s.get("raw-initial-ground-truth") or []) for s in samples]
    total_args = int(np.sum(arg_counts))

    # 4) Document-level argument density = total arguments / unique documents
    doc_id_key = doc_id_keys[dataset_name]
    unique_doc_ids = {
        s.get(doc_id_key)
        for s in samples
        if s.get(doc_id_key) is not None
    }
    num_unique_docs = len(unique_doc_ids)
    args_per_doc = (total_args / num_unique_docs) if num_unique_docs > 0 else 0

    # 5) Avg argument length in words (across all individual arguments)
    arg_word_lengths = []
    for s in samples:
        for arg in (s.get("raw-initial-ground-truth") or []):
            if isinstance(arg, str):
                arg_word_lengths.append(len(arg.split()))

    stats = {
        "Total samples": len(samples),
        "Unique docs": num_unique_docs,
        "Total arguments": total_args,
        "Unique roles": len(roles),
        "Role list": sorted(roles),
        "Avg context length (words)": np.mean(ctx_lengths),
        "Median context length (words)": np.median(ctx_lengths),
        "Min / Max context length": (min(ctx_lengths), max(ctx_lengths)),
        "Argument density (args/doc)": args_per_doc,
        "Avg argument length (words)": np.mean(arg_word_lengths) if arg_word_lengths else 0,
        "Median argument length (words)": np.median(arg_word_lengths) if arg_word_lengths else 0,
    }
    all_stats[dataset_name] = stats

    print(f"\n{'='*60}")
    print(f"  {dataset_name}")
    print(f"{'='*60}")
    for k, v in stats.items():
        if isinstance(v, float):
            print(f"  {k:40s}: {v:.2f}")
        else:
            print(f"  {k:40s}: {v}")

Reading JSON file from: /dartfs-hpc/rc/home/j/f006f3j/lab/omar/LoQA/Dataset/CaseReportBench/CaseReportBench-train.json
Reading JSON file from: /dartfs-hpc/rc/home/j/f006f3j/lab/omar/LoQA/Dataset/CaseReportBench/CaseReportBench-dev.json
Reading JSON file from: /dartfs-hpc/rc/home/j/f006f3j/lab/omar/LoQA/Dataset/CaseReportBench/CaseReportBench-test.json

============================================================
  CaseReportBench
============================================================
  Total samples                           : 1320
  Unique docs                             : 138
  Total arguments                         : 3555
  Unique roles                            : 18
  Role list                               : ['Age-at-Presentation', 'Age-of-Onset', 'Cardiovascular-System', 'Confirmed-Diagnosis-IEM', 'Dermatology', 'Endocrinology', 'Eyes-Ears-Nose-Throat', 'Gastrointestinal-System', 'Genitourinary-System', 'IEM-Treatment', 'Laboratory-and-Imaging', 'Lymphatic-System', 'Musculoskeletal-System', 'Neurology', 'Patient-History', 'Pregnancy', 'Respiratory-System', 'Vitals-and-Hematology']
  Avg context length (words)              : 581.66
  Median context length (words)           : 521.00
  Min / Max context length                : (154, 1922)
  Argument density (args/doc)             : 25.76
  Avg argument length (words)             : 20.71
  Median argument length (words)          : 10.00
Reading JSON file from: /dartfs-hpc/rc/home/j/f006f3j/lab/omar/LoQA/Dataset/PHEE/PHEE-train.json
Reading JSON file from: /dartfs-hpc/rc/home/j/f006f3j/lab/omar/LoQA/Dataset/PHEE/PHEE-dev.json
Reading JSON file from: /dartfs-hpc/rc/home/j/f006f3j/lab/omar/LoQA/Dataset/PHEE/PHEE-test.json

============================================================
  PHEE
============================================================
  Total samples                           : 22274
  Unique docs                             : 4827
  Total arguments                         : 24454
  Unique roles                            : 14
  Role list                               : ['effect', 'subject', 'subject-age', 'subject-disorder', 'subject-gender', 'subject-population', 'subject-race', 'treatment', 'treatment-disorder', 'treatment-dosage', 'treatment-drug', 'treatment-duration', 'treatment-freq', 'treatment-route']
  Avg context length (words)              : 19.74
  Median context length (words)           : 19.00
  Min / Max context length                : (2, 75)
  Argument density (args/doc)             : 5.07
  Avg argument length (words)             : 2.45
  Median argument length (words)          : 2.00
Reading JSON file from: /dartfs-hpc/rc/home/j/f006f3j/lab/omar/LoQA/Dataset/DiscourseEE/DiscourseEE-train.json
Reading JSON file from: /dartfs-hpc/rc/home/j/f006f3j/lab/omar/LoQA/Dataset/DiscourseEE/DiscourseEE-dev.json
Reading JSON file from: /dartfs-hpc/rc/home/j/f006f3j/lab/omar/LoQA/Dataset/DiscourseEE/DiscourseEE-test.json

============================================================
  DiscourseEE
============================================================
  Total samples                           : 3222
  Unique docs                             : 392
  Total arguments                         : 3709
  Unique roles                            : 34
  Role list                               : ['age', 'condition', 'conditions', 'current-dosage', 'dosage', 'effects', 'existing/current-medications', 'frequency', 'gender', 'goal-dosage', 'initial-dosage', 'intervention', 'manner', 'medications', 'purpose', 'relapse-duration', 'relapse-event', 'relapse-intervention', 'relapse-substance', 'resuming-moud-after-relapse', 'severity', 'side-effect-duration', 'side-effects', 'start-time', 'subject/patient', 'taper-medications', 'tapering-event', 'target-duration', 'timing', 'treatment', 'treatment-duration', 'trigger', 'type', 'waiting-time']
  Avg context length (words)              : 120.75
  Median context length (words)           : 118.00
  Min / Max context length                : (32, 248)
  Argument density (args/doc)             : 9.46
  Avg argument length (words)             : 3.04
  Median argument length (words)          : 2.00
Reading JSON file from: /dartfs-hpc/rc/home/j/f006f3j/lab/omar/LoQA/Dataset/MACCROBAT/MACCROBAT-train.json
Reading JSON file from: /dartfs-hpc/rc/home/j/f006f3j/lab/omar/LoQA/Dataset/MACCROBAT/MACCROBAT-dev.json
Reading JSON file from: /dartfs-hpc/rc/home/j/f006f3j/lab/omar/LoQA/Dataset/MACCROBAT/MACCROBAT-test.json

============================================================
  MACCROBAT
============================================================
  Total samples                           : 6882
  Unique docs                             : 200
  Total arguments                         : 8120
  Unique roles                            : 22
  Role list                               : ['Administration', 'Age', 'Area', 'Biological_attribute', 'Biological_structure', 'Color', 'Detailed_description', 'Distance', 'Dosage', 'Frequency', 'History', 'Lab_value', 'Mass', 'Nonbiological_location', 'Other_entity', 'Qualitative_concept', 'Quantitative_concept', 'Severity', 'Shape', 'Subject', 'Texture', 'Volume']
  Avg context length (words)              : 24.17
  Median context length (words)           : 22.00
  Min / Max context length                : (4, 93)
  Argument density (args/doc)             : 40.60
  Avg argument length (words)             : 1.73
  Median argument length (words)          : 1.00

In [9]:
import pandas as pd

ordered_names = ["CaseReportBench", "PHEE", "DiscourseEE", "MACCROBAT"]
rows = []
for name in ordered_names:
    st = all_stats[name]
    rows.append({
        "Dataset": name,
        "Samples": st["Total samples"],
        "Unique Docs": st["Unique docs"],
        "Total Args": st["Total arguments"],
        "Unique Roles": st["Unique roles"],
        "Avg Ctx Len (words)": round(st["Avg context length (words)"], 1),
        "Med Ctx Len (words)": round(st["Median context length (words)"], 1),
        "Arg Density (args/doc)": round(st["Argument density (args/doc)"], 2),
        "Avg Arg Len (words)": round(st["Avg argument length (words)"], 2),
        "Med Arg Len (words)": round(st["Median argument length (words)"], 2),
    })

df = pd.DataFrame(rows)
df

,Dataset,Samples,Unique Docs,Total Args,Unique Roles,Avg Ctx Len (words),Med Ctx Len (words),Arg Density (args/doc),Avg Arg Len (words),Med Arg Len (words)
0,CaseReportBench,1320,138,3555,18,581.7,521.0,25.76,20.71,10.0
1,PHEE,22274,4827,24454,14,19.7,19.0,5.07,2.45,2.0
2,DiscourseEE,3222,392,3709,34,120.8,118.0,9.46,3.04,2.0
3,MACCROBAT,6882,200,8120,22,24.2,22.0,40.60,1.73,1.0

## Creating test splits for DocEE and GENEVA

In [8]:
import os
import sys
import json
import random

REPO_ROOT = '/dartfs-hpc/rc/home/j/f006f3j/lab/omar/LoQA'
if REPO_ROOT not in sys.path:
    sys.path.insert(0, REPO_ROOT)

from Code.src.utils.io import read_json_file, save_json_file


def is_valid_sample(sample):
    """Check if a sample is valid (has non-null, non-empty raw-initial-ground-truth)."""
    arg_value = sample.get("raw-initial-ground-truth", None)
    if arg_value is None:
        return False
    if isinstance(arg_value, (list, str)) and len(arg_value) == 0:
        return False
    if isinstance(arg_value, list) and len(arg_value) == 1 and arg_value[0] == "null":
        return False
    return True


def filter_valid_samples(samples):
    """Filter out invalid samples (where raw-initial-ground-truth is None, empty, or "null")."""
    return [sample for sample in samples if is_valid_sample(sample)]


def dedup_by_context_role_gt(samples):
    """Ensure no duplicate (context, role, raw-initial-ground-truth) appears more than once."""
    seen = set()
    unique = []
    for s in samples:
        ctx = s.get("context")
        role = s.get("role")
        gt = tuple(s.get("raw-initial-ground-truth") or [])
        key = (ctx, role, gt)
        if key in seen:
            continue
        seen.add(key)
        unique.append(s)
    return unique


def make_clean_role(event, role):
    """Build an LLM-friendly role name from event and role: 'event name: role name'."""
    def _normalize(s):
        return " ".join(s.replace("_", " ").replace(" - ", " ").replace("-", " ").split()).lower()
    return f"{_normalize(event)}: {_normalize(role)}"


dataset_root = '/dartfs-hpc/rc/home/j/f006f3j/lab/omar/LoQA/Dataset'
seed = 42
test_count = 500

datasets_config = {
    "DocEE": {
        "source_file": "DocEE-processed-test-data-EAE-Eval.json",
        "doc_id_key": "id",
    },
    "GENEVA": {
        "source_file": "GENEVA-processed-test-data-EAE-Eval.json",
        "doc_id_key": "id",
    },
}

random.seed(seed)

for dataset_name, config in datasets_config.items():
    print(f"\n{'='*60}")
    print(f"  Creating test split for {dataset_name}")
    print(f"{'='*60}")

    source_path = os.path.join(dataset_root, dataset_name, config["source_file"])
    all_samples = read_json_file(source_path)
    print(f"Loaded {len(all_samples)} total samples from {config['source_file']}")

    valid_samples = filter_valid_samples(all_samples)
    print(f"Valid samples: {len(valid_samples)}  (filtered out {len(all_samples) - len(valid_samples)} invalid)")

    unique_samples = dedup_by_context_role_gt(valid_samples)
    print(f"Unique samples (by context, role, GT): {len(unique_samples)}  (removed {len(valid_samples) - len(unique_samples)} duplicates)")

    doc_id_key = config["doc_id_key"]
    total_docs = {s.get(doc_id_key) for s in unique_samples if s.get(doc_id_key) is not None}
    print(f"Unique documents: {len(total_docs)}")

    if len(unique_samples) < test_count:
        print(f"WARNING: Only {len(unique_samples)} unique samples available, less than {test_count}. Using all.")
        test_count_actual = len(unique_samples)
    else:
        test_count_actual = test_count

    random.shuffle(unique_samples)
    test_samples = unique_samples[:test_count_actual]

    for idx, sample in enumerate(test_samples, start=1):
        sample["serial-number"] = f"test-{idx}"

    for sample in test_samples:
        sample["old-role"] = sample.get("role")
        event = sample.get("event", "")
        old_role = sample.get("role", "")
        if event and old_role:
            sample["role"] = make_clean_role(event, old_role)

    selected_docs = {s.get(doc_id_key) for s in test_samples if s.get(doc_id_key) is not None}
    print(f"\nSelected {len(test_samples)} test samples from {len(selected_docs)} unique documents (out of {len(total_docs)} total)")

    event_counts = {}
    for s in test_samples:
        ev = s.get("event", "unknown")
        event_counts[ev] = event_counts.get(ev, 0) + 1
    print(f"Event type distribution in test set ({len(event_counts)} types):")
    for ev, cnt in sorted(event_counts.items(), key=lambda x: -x[1]):
        print(f"  {ev:40s}: {cnt}")

    out_path = os.path.join(dataset_root, dataset_name, f"{dataset_name}-test.json")
    save_json_file(test_samples, out_path)
    print(f"\nSaved test split to: {out_path}")

============================================================
  Creating test split for DocEE
============================================================
Reading JSON file from: /dartfs-hpc/rc/home/j/f006f3j/lab/omar/LoQA/Dataset/DocEE/DocEE-processed-test-data-EAE-Eval.json
Loaded 2368 total samples from DocEE-processed-test-data-EAE-Eval.json
Valid samples: 2368  (filtered out 0 invalid)
Unique samples (by context, role, GT): 2368  (removed 0 duplicates)
Unique documents: 500

Selected 500 test samples from 322 unique documents (out of 500 total)
Event type distribution in test set (53 types):
  air crash                               : 51
  armed conflict                          : 32
  sports competition                      : 29
  protest                                 : 28
  strike                                  : 21
  commitcrime - sentence                  : 18
  earthquakes                             : 17
  disease outbreaks                       : 16
  fire                                    : 15
  resignation_dismissal                   : 15
  diplomatic talks                        : 15
  election                                : 14
  floods                                  : 13
  riot                                    : 13
  famous person - death                   : 13
  government policy changes               : 11
  sign agreement                          : 11
  commitcrime - accuse                    : 10
  break historical records                : 9
  commitcrime - arrest                    : 9
  appoint_inauguration                    : 8
  organization fine                       : 8
  storm                                   : 8
  bank robbery                            : 8
  shipwreck                               : 7
  organization closed                     : 7
  awards ceremony                         : 7
  mass poisoning                          : 6
  insect disaster                         : 6
  famous person - give a speech           : 6
  gas explosion                           : 5
  train collisions                        : 5
  famous person - divorce                 : 5
  volcano eruption                        : 5
  organization merge                      : 5
  road crash                              : 4
  withdraw from an orgnization            : 4
  new wonders in nature                   : 4
  financial aid                           : 3
  new achievements in aerospace           : 3
  join in an orgnization                  : 3
  financial crisis                        : 3
  mine collapses                          : 3
  military excercise                      : 3
  diplomatic visit                        : 2
  tear up agreement                       : 2
  commitcrime - investigate               : 2
  famous person - recovered               : 2
  commitcrime - release                   : 2
  mudslides                               : 1
  organization established                : 1
  new archeological discoveries           : 1
  environment pollution                   : 1
Data saved to: /dartfs-hpc/rc/home/j/f006f3j/lab/omar/LoQA/Dataset/DocEE/DocEE-test.json

Saved test split to: /dartfs-hpc/rc/home/j/f006f3j/lab/omar/LoQA/Dataset/DocEE/DocEE-test.json

============================================================
  Creating test split for GENEVA
============================================================
Reading JSON file from: /dartfs-hpc/rc/home/j/f006f3j/lab/omar/LoQA/Dataset/GENEVA/GENEVA-processed-test-data-EAE-Eval.json
Loaded 2866 total samples from GENEVA-processed-test-data-EAE-Eval.json
Valid samples: 2866  (filtered out 0 invalid)
Unique samples (by context, role, GT): 2835  (removed 31 duplicates)
Unique documents: 90

Selected 500 test samples from 74 unique documents (out of 90 total)
Event type distribution in test set (108 types):
  statement                               : 29
  action                                  : 21
  assistance                              : 19
  causation                               : 19
  using                                   : 18
  building                                : 15
  supply                                  : 15
  arriving                                : 14
  manufacturing                           : 13
  process_start                           : 13
  sending                                 : 11
  creating                                : 11
  telling                                 : 10
  getting                                 : 9
  convincing                              : 9
  motion                                  : 8
  traveling                               : 8
  killing                                 : 8
  connect                                 : 8
  communication                           : 8
  scrutiny                                : 7
  process_end                             : 7
  judgment_communication                  : 6
  presence                                : 6
  catastrophe                             : 5
  coming_to_believe                       : 5
  change                                  : 5
  placing                                 : 5
  research                                : 5
  education_teaching                      : 5
  commerce_buy                            : 5
  hostile_encounter                       : 5
  sign_agreement                          : 5
  cause_change_of_position_on_a_scale     : 4
  cause_to_make_progress                  : 4
  getready                                : 4
  practice                                : 4
  expansion                               : 4
  perception_active                       : 4
  terrorism                               : 4
  commerce_sell                           : 3
  request                                 : 3
  know                                    : 3
  choosing                                : 3
  cause_to_amalgamate                     : 3
  bringing                                : 3
  committing_crime                        : 3
  earnings_and_losses                     : 3
  agree_or_refuse_to_act                  : 3
  participation                           : 3
  filling                                 : 3
  defending                               : 3
  reveal_secret                           : 3
  come_together                           : 3
  collaboration                           : 3
  conquering                              : 3
  preventing_or_letting                   : 3
  hold                                    : 2
  containing                              : 2
  employment                              : 2
  influence                               : 2
  death                                   : 2
  adducing                                : 2
  deciding                                : 2
  ratification                            : 2
  achieve                                 : 2
  receiving                               : 2
  giving                                  : 2
  becoming                                : 2
  change_of_leadership                    : 2
  writing                                 : 2
  ingestion                               : 2
  emergency                               : 2
  exchange                                : 2
  labeling                                : 2
  coming_to_be                            : 2
  cost                                    : 2
  criminal_investigation                  : 2
  attack                                  : 2
  check                                   : 2
  motion_directional                      : 2
  create_artwork                          : 2
  emptying                                : 2
  self_motion                             : 2
  bearing_arms                            : 2
  protest                                 : 2
  arrest                                  : 2
  wearing                                 : 2
  removing                                : 2
  resolve_problem                         : 2
  social_event                            : 1
  cure                                    : 1
  commerce_pay                            : 1
  revenge                                 : 1
  confronting_problem                     : 1
  destroying                              : 1
  damaging                                : 1
  arranging                               : 1
  control                                 : 1
  legality                                : 1
  competition                             : 1
  hindering                               : 1
  rite                                    : 1
  openness                                : 1
  bodily_harm                             : 1
  quarreling                              : 1
  response                                : 1
  departing                               : 1
Data saved to: /dartfs-hpc/rc/home/j/f006f3j/lab/omar/LoQA/Dataset/GENEVA/GENEVA-test.json

Saved test split to: /dartfs-hpc/rc/home/j/f006f3j/lab/omar/LoQA/Dataset/GENEVA/GENEVA-test.json

In [9]:
import os
import sys
import json
import numpy as np
import pandas as pd

REPO_ROOT = '/dartfs-hpc/rc/home/j/f006f3j/lab/omar/LoQA'
if REPO_ROOT not in sys.path:
    sys.path.insert(0, REPO_ROOT)

from Code.src.utils.io import read_json_file

dataset_root = '/dartfs-hpc/rc/home/j/f006f3j/lab/omar/LoQA/Dataset'

new_datasets = {
    "DocEE": {"doc_id_key": "id"},
    "GENEVA": {"doc_id_key": "id"},
}

all_stats = {}

for dataset_name, config in new_datasets.items():
    test_path = os.path.join(dataset_root, dataset_name, f"{dataset_name}-test.json")
    samples = read_json_file(test_path)
    doc_id_key = config["doc_id_key"]

    roles = set(s.get("role", "") for s in samples)
    events = set(s.get("event", "") for s in samples)

    ctx_lengths = [len(s.get("context", "").split()) for s in samples]

    arg_counts = [len(s.get("raw-initial-ground-truth") or []) for s in samples]
    total_args = int(np.sum(arg_counts))

    unique_doc_ids = {s.get(doc_id_key) for s in samples if s.get(doc_id_key) is not None}
    num_unique_docs = len(unique_doc_ids)
    args_per_doc = (total_args / num_unique_docs) if num_unique_docs > 0 else 0

    arg_word_lengths = []
    for s in samples:
        for arg in (s.get("raw-initial-ground-truth") or []):
            if isinstance(arg, str):
                arg_word_lengths.append(len(arg.split()))

    stats = {
        "Test samples": len(samples),
        "Unique docs": num_unique_docs,
        "Unique event types": len(events),
        "Total arguments": total_args,
        "Unique roles": len(roles),
        "Role list": sorted(roles),
        "Avg context length (words)": np.mean(ctx_lengths),
        "Median context length (words)": np.median(ctx_lengths),
        "Min / Max context length": (min(ctx_lengths), max(ctx_lengths)),
        "Argument density (args/doc)": args_per_doc,
        "Avg argument length (words)": np.mean(arg_word_lengths) if arg_word_lengths else 0,
        "Median argument length (words)": np.median(arg_word_lengths) if arg_word_lengths else 0,
    }
    all_stats[dataset_name] = stats

    print(f"\n{'='*60}")
    print(f"  {dataset_name} (test split)")
    print(f"{'='*60}")
    for k, v in stats.items():
        if isinstance(v, float):
            print(f"  {k:40s}: {v:.2f}")
        else:
            print(f"  {k:40s}: {v}")

rows = []
for name in ["DocEE", "GENEVA"]:
    st = all_stats[name]
    rows.append({
        "Dataset": name,
        "Test Samples": st["Test samples"],
        "Unique Docs": st["Unique docs"],
        "Event Types": st["Unique event types"],
        "Total Args": st["Total arguments"],
        "Unique Roles": st["Unique roles"],
        "Avg Ctx Len (words)": round(st["Avg context length (words)"], 1),
        "Med Ctx Len (words)": round(st["Median context length (words)"], 1),
        "Arg Density (args/doc)": round(st["Argument density (args/doc)"], 2),
        "Avg Arg Len (words)": round(st["Avg argument length (words)"], 2),
        "Med Arg Len (words)": round(st["Median argument length (words)"], 2),
    })

df = pd.DataFrame(rows)
df

Reading JSON file from: /dartfs-hpc/rc/home/j/f006f3j/lab/omar/LoQA/Dataset/DocEE/DocEE-test.json

============================================================
  DocEE (test split)
============================================================
  Test samples                            : 500
  Unique docs                             : 322
  Unique event types                      : 53
  Total arguments                         : 749
  Unique roles                            : 238
  Role list                               : ['air crash: accident investigator', 'air crash: aircraft agency', 'air crash: casualties and losses', 'air crash: cause', 'air crash: crew', 'air crash: date', 'air crash: flight no.', 'air crash: location', 'air crash: passengers', 'air crash: scheduled landing place', 'air crash: survivors', 'appoint inauguration: appointee', 'appoint inauguration: inauguration time', 'appoint inauguration: last job of the appointee', 'appoint inauguration: position', 'appoint inauguration: predecessor', 'armed conflict: attacker', 'armed conflict: casualties and losses', 'armed conflict: damaged facility', 'armed conflict: date', 'armed conflict: location', 'armed conflict: target', 'armed conflict: weapon and equippment', 'awards ceremony: award field', 'awards ceremony: date', 'awards ceremony: employed institution', 'bank robbery: bank name', 'bank robbery: date', 'bank robbery: investigating agency', 'bank robbery: investigating spokesperson', 'bank robbery: location', 'bank robbery: perpetrators', 'bank robbery: transportation', 'break historical records: date', 'break historical records: previous record holder', 'break historical records: record breaker', 'break historical records: record breaking project', 'break historical records: the grades of the previous record holder', 'commitcrime accuse: accused people', 'commitcrime accuse: charged crime', 'commitcrime accuse: defense lawyer', 'commitcrime accuse: evidence', 'commitcrime accuse: time of the case', 'commitcrime arrest: arrest location', 'commitcrime arrest: police', 'commitcrime arrest: suspect', 'commitcrime arrest: the charged crime', 'commitcrime investigate: investigative agency', 'commitcrime release: release reason', 'commitcrime release: released people', 'commitcrime sentence: accusation', 'commitcrime sentence: court', 'commitcrime sentence: court time', 'commitcrime sentence: defense lawyer', 'commitcrime sentence: judge', 'commitcrime sentence: judgement result/prison term', 'commitcrime sentence: suspect', "commitcrime sentence: the sentence claimed by the prosecutor's lawyer", 'commitcrime sentence: victim', 'diplomatic talks: date', 'diplomatic talks: location', 'diplomatic talks: participants', 'diplomatic talks: summit name', 'diplomatic talks: summit theme', 'diplomatic visit: country visited', 'diplomatic visit: visitor', 'disease outbreaks: confirmed/infected cases', 'disease outbreaks: cured rate', 'disease outbreaks: date', 'disease outbreaks: death cases', 'disease outbreaks: death rate', 'disease outbreaks: disease', 'disease outbreaks: epidemic data issuing agency', 'disease outbreaks: number of people hospitalized', 'disease outbreaks: precautionary measure', 'disease outbreaks: vaccine research and development organization', 'earthquakes: affected area', 'earthquakes: casualties and losses', 'earthquakes: date', 'earthquakes: economic loss', 'earthquakes: magnitude', 'earthquakes: number of aftershocks', 'earthquakes: number of destroyed building', 'election: candidates and their political parties', 'election: date', 'election: election goal', 'election: location', 'election: the final votes and percentages', 'election: voting method', 'environment pollution: pollution source', 'famous person death: age', 'famous person death: date', 'famous person death: deceased', 'famous person death: location/hospital', 'famous person death: profession', 'famous person divorce: child custody', 'famous person divorce: date', 'famous person divorce: husband', 'famous person divorce: property division', 'famous person divorce: wife', 'famous person give a speech: location', 'famous person give a speech: news release agency', 'famous person give a speech: speaker', 'famous person give a speech: speaker status', 'famous person recovered: disease', 'famous person recovered: location/hospital', 'financial aid: date', 'financial aid: location', 'financial aid: sponsor', 'financial crisis: affected industries', 'fire: aid agency', 'fire: casualties and losses', 'fire: cause', 'fire: date', 'fire: location', 'fire: number of damaged houses', 'fire: temporary settlement', 'floods: affected areas', 'floods: aid agency', 'floods: casualties and losses', 'floods: cause', 'floods: date', 'floods: economic loss', 'floods: maximum rainfall', 'floods: missings', 'floods: number of damaged houses', 'gas explosion: accident investigator', 'gas explosion: casualties and losses', 'gas explosion: location', 'government policy changes: announcement date', 'government policy changes: deliberating agency', 'government policy changes: effective date', 'government policy changes: location', 'government policy changes: policy content', 'insect disaster: affected areas', 'insect disaster: aid supplies/amount', 'insect disaster: date', 'insect disaster: influenced crops and livelihood', 'insect disaster: pests', 'join in an orgnization: countries joined the organization', 'join in an orgnization: effective date', 'join in an orgnization: organization leader', 'mass poisoning: accident investigator', 'mass poisoning: casualties and losses', 'mass poisoning: date', 'mass poisoning: poisoning type', 'military excercise: location', 'military excercise: participating countries', 'military excercise: weapon and equippment', 'mine collapses: accident investigator', 'mine collapses: casualties and losses', 'mine collapses: number of trapped people', 'mudslides: date', 'new achievements in aerospace: carrier rocket', 'new achievements in aerospace: launch site', 'new achievements in aerospace: research agency', 'new archeological discoveries: historical sites', 'new wonders in nature: best way to shoot', 'new wonders in nature: forecasting agency', 'new wonders in nature: spectacle location', 'organization closed: cause', 'organization closed: date', 'organization closed: organization', 'organization established: spokenmen', 'organization fine: fine reason', 'organization fine: fined agency', 'organization fine: location', 'organization fine: penalty amount', 'organization merge: acquiree', 'organization merge: acquirer', 'organization merge: date', 'protest: casualties and losses', 'protest: damaged property', 'protest: date', 'protest: location', 'protest: method', 'protest: protest reason', 'protest: protesters', 'resignation dismissal: age of the resignated person', 'resignation dismissal: date', 'resignation dismissal: position', 'resignation dismissal: resign reason', 'resignation dismissal: resignated person', 'resignation dismissal: successor', 'riot: belligerents', 'riot: casualties and losses', 'riot: date', 'riot: location', 'riot: weapon', 'road crash: accident investigator', 'road crash: casualties and losses', 'road crash: cause', 'shipwreck: casualties and losses', 'shipwreck: date', 'shipwreck: location', 'shipwreck: rescue organizer', 'shipwreck: rescue tool or method', 'shipwreck: ship no.', 'sign agreement: agreement content', 'sign agreement: agreement name', 'sign agreement: date', 'sign agreement: location', 'sports competition: champions', 'sports competition: competition items', 'sports competition: contest participant', 'sports competition: end time', 'sports competition: game name', 'sports competition: host country', 'sports competition: location', 'sports competition: score', 'sports competition: start time', 'storm: amount of precipitation', 'storm: influence people', 'storm: storm hit location', 'storm: storm hit time', 'storm: storm name', 'strike: boycotted institutions', 'strike: duration', 'strike: end date', 'strike: start date', 'strike: strike agency', 'strike: strike industry', 'strike: strike reason', 'strike: strikers', 'strike: strikers status', 'tear up agreement: agreement name', 'tear up agreement: the agency who broke the agreement', 'train collisions: casualties and losses', 'train collisions: date', 'train collisions: location', 'volcano eruption: affected areas', 'volcano eruption: economic loss', 'volcano eruption: outbreak date', 'volcano eruption: the state of the volcano (dormant or active)', 'withdraw from an orgnization: annoncement date', 'withdraw from an orgnization: countries withdrawing from the organization', 'withdraw from an orgnization: declarer', 'withdraw from an orgnization: organization name']
  Avg context length (words)              : 643.18
  Median context length (words)           : 529.50
  Min / Max context length                : (53, 2974)
  Argument density (args/doc)             : 2.33
  Avg argument length (words)             : 4.00
  Median argument length (words)          : 3.00
Reading JSON file from: /dartfs-hpc/rc/home/j/f006f3j/lab/omar/LoQA/Dataset/GENEVA/GENEVA-test.json

============================================================
  GENEVA (test split)
============================================================
  Test samples                            : 500
  Unique docs                             : 74
  Unique event types                      : 108
  Total arguments                         : 538
  Unique roles                            : 218
  Role list                               : ['achieve: goal', 'achieve: means', 'action: act', 'action: agent', 'action: domain', 'adducing: speaker', 'agree or refuse to act: proposed action', 'agree or refuse to act: speaker', 'arranging: theme', 'arrest: suspect', 'arriving: goal', 'arriving: purpose', 'arriving: theme', 'assistance: benefited party', 'assistance: goal', 'assistance: helper', 'attack: victim', 'bearing arms: protagonist', 'becoming: entity', 'becoming: final category', 'bodily harm: victim', 'bringing: agent', 'bringing: goal', 'bringing: theme', 'building: agent', 'building: components', 'building: created entity', 'building: place', 'catastrophe: cause', 'catastrophe: patient', 'catastrophe: undesirable event', 'causation: actor', 'causation: affected', 'causation: cause', 'causation: effect', 'cause change of position on a scale: agent', 'cause change of position on a scale: attribute', 'cause change of position on a scale: item', 'cause change of position on a scale: value 2', 'cause to amalgamate: parts', 'cause to make progress: agent', 'cause to make progress: project', 'change of leadership: old leader', 'change of leadership: selector', 'change: agent', 'change: attribute', 'change: cause', 'change: entity', 'check: inspector', 'check: unconfirmed content', 'choosing: chosen', 'choosing: cognizer', 'collaboration: partners', 'come together: configuration', 'come together: individuals', 'coming to be: place', 'coming to believe: cognizer', 'coming to believe: content', 'commerce buy: buyer', 'commerce buy: goods', 'commerce pay: buyer', 'commerce sell: goods', 'commerce sell: seller', 'committing crime: crime', 'committing crime: perpetrator', 'communication: interlocutors', 'communication: message', 'communication: topic', 'competition: participants', 'confronting problem: activity', 'connect: figures', 'connect: ground', 'conquering: conqueror', 'conquering: theme', 'containing: container', 'control: controlling variable', 'convincing: addressee', 'convincing: content', 'convincing: speaker', 'cost: goods', 'cost: intended event', 'create artwork: activity', 'create artwork: culture', 'creating: created entity', 'creating: creator', 'criminal investigation: incident', 'criminal investigation: investigator', 'cure: affliction', 'damaging: patient', 'death: deceased', 'deciding: cognizer', 'defending: assailant', 'defending: victim', 'departing: traveller', 'destroying: destroyer', 'earnings and losses: earnings', 'education teaching: student', 'education teaching: subject', 'education teaching: teacher', 'emergency: undesirable event', 'employment: employee', 'employment: task', 'emptying: source', 'emptying: theme', 'exchange: exchangers', 'exchange: themes', 'expansion: agent', 'expansion: item', 'filling: goal', 'filling: theme', 'getready: activity', 'getready: protagonist', 'getting: recipient', 'getting: theme', 'giving: theme', 'hindering: hindrance', 'hold: entity', 'hold: manipulator', 'hostile encounter: instrument', 'hostile encounter: side 1', 'hostile encounter: side 2', 'hostile encounter: sides', 'influence: behavior', 'influence: cognizer', 'ingestion: ingestibles', 'ingestion: ingestor', 'judgment communication: addressee', 'judgment communication: communicator', 'judgment communication: evaluee', 'killing: instrument', 'killing: killer', 'killing: victim', 'know: phenomenon', 'labeling: entity', 'labeling: speaker', 'legality: action', 'manufacturing: factory', 'manufacturing: producer', 'manufacturing: product', 'motion directional: goal', 'motion directional: path', 'motion: cause', 'motion: speed', 'motion: theme', 'openness: barrier', 'participation: event', 'participation: participants', 'perception active: direction', 'perception active: perceiver agentive', 'perception active: phenomenon', 'placing: location', 'placing: theme', 'practice: action', 'practice: agent', 'practice: occasion', 'presence: circumstances', 'presence: entity', 'preventing or letting: agent', 'preventing or letting: event', 'process end: agent', 'process end: final subevent', 'process end: process', 'process end: state', 'process start: agent', 'process start: event', 'process start: initial subevent', 'process start: time', 'protest: arguer', 'quarreling: issue', 'ratification: proposal', 'ratification: ratifier', 'receiving: recipient', 'receiving: theme', 'removing: goal', 'removing: theme', 'request: addressee', 'request: speaker', 'research: researcher', 'research: topic', 'resolve problem: problem', 'response: trigger', 'reveal secret: information', 'reveal secret: speaker', 'reveal secret: topic', 'revenge: avenger', 'rite: member', 'scrutiny: cognizer', 'scrutiny: ground', 'self motion: goal', 'self motion: path', 'sending: recipient', 'sending: sender', 'sending: theme', 'sign agreement: agreement', 'sign agreement: signatory', 'social event: occasion', 'statement: message', 'statement: speaker', 'supply: imposed purpose', 'supply: recipient', 'supply: supplier', 'supply: theme', 'telling: addressee', 'telling: message', 'telling: speaker', 'terrorism: act', 'terrorism: instrument', 'terrorism: terrorist', 'traveling: entity', 'traveling: goal', 'traveling: traveler', 'using: agent', 'using: instrument', 'using: purpose', 'wearing: clothing', 'wearing: wearer', 'writing: author', 'writing: text']
  Avg context length (words)              : 30.90
  Median context length (words)           : 29.00
  Min / Max context length                : (3, 107)
  Argument density (args/doc)             : 7.27
  Avg argument length (words)             : 5.24
  Median argument length (words)          : 3.00

,Dataset,Test Samples,Unique Docs,Event Types,Total Args,Unique Roles,Avg Ctx Len (words),Med Ctx Len (words),Arg Density (args/doc),Avg Arg Len (words),Med Arg Len (words)
0,DocEE,500,322,53,749,238,643.2,529.5,2.33,4.00,3.0
1,GENEVA,500,74,108,538,218,30.9,29.0,7.27,5.24,3.0

## previously used this code

## Preparing the gold test data

In [9]:
def is_valid_sample(sample):
    """Check if a sample is valid (has non-null, non-empty raw-initial-ground-truth)."""
    arg_value = sample.get("raw-initial-ground-truth", None)
    if arg_value is None:
        return False
    if isinstance(arg_value, (list, str)) and len(arg_value) == 0:
        return False
    if isinstance(arg_value, list) and len(arg_value) == 1 and arg_value[0] == "null":
        return False
    return True


def filter_valid_samples(samples):
    """Filter out invalid samples (where raw-initial-ground-truth is None, empty, or "null")."""
    return [sample for sample in samples if is_valid_sample(sample)]


def get_unique_documents(samples, doc_id_key):
    """Get set of unique document IDs from samples."""
    return {sample.get(doc_id_key) for sample in samples if sample.get(doc_id_key) is not None}


def create_gold_test_set(processed_data, dataset_name, split_name, sample_count=500):
    """
    Create a gold set based on the split name by selecting samples only from that split.
    
    Args:
        processed_data: Dictionary with split keys ('train', 'dev', 'test')
        dataset_name: Name of the dataset ('DiscourseEE', 'PHEE', or 'CaseReportBench')
        split_name: Name of the split to use ('train', 'dev', or 'test')
        sample_count: Number of samples to select
    
    Returns:
        List of selected samples
    """
    # Determine document ID key
    doc_id_keys = {
        "DiscourseEE": "doc_id",
        "PHEE": "id",
        "CaseReportBench": "pmcid",
        "MACCROBAT": "doc_id"
    }
    doc_id_key = doc_id_keys.get(dataset_name)
    if doc_id_key is None:
        raise ValueError(f"Unknown dataset: {dataset_name}")
    
    # Get samples only from the specified split
    all_samples = processed_data.get(split_name, [])
    if not all_samples:
        raise ValueError(f"Split '{split_name}' not found in processed_data")
    
    print(f"\nTotal {split_name} samples available: {len(all_samples)}")
    
    # Filter valid samples
    valid_samples = filter_valid_samples(all_samples)
    invalid_count = len(all_samples) - len(valid_samples)
    print(f"Valid {split_name} samples: {len(valid_samples)}")
    print(f"Invalid {split_name} samples filtered out: {invalid_count}")
    
    # Calculate total unique documents
    total_docs = get_unique_documents(valid_samples, doc_id_key)
    print(f"Total unique documents in {split_name} split: {len(total_docs)}")
    
    # Randomly sample samples
    print(f"\nRandomly selecting {sample_count} samples from {split_name} split for gold set...")
    random.shuffle(valid_samples)
    selected_samples = valid_samples[:sample_count]
    
    # Calculate document coverage
    selected_doc_ids = get_unique_documents(selected_samples, doc_id_key)
    print(f"Selected {len(selected_samples)} samples from {len(selected_doc_ids)} unique documents (out of {len(total_docs)} total documents)")
    
    return selected_samples

In [ ]:
# # Set random seed for reproducibility
# random.seed(42)
# data_path = '/dartfs-hpc/rc/home/j/f006f3j/lab/omar/LoQA/Dataset'
# # Process each dataset to create gold test sets
# datasets_to_process = ["DiscourseEE", "PHEE", "CaseReportBench", "MACCROBAT"]

# for dataset_name in datasets_to_process:
#     print(f"\n{'='*60}")
#     print(f"Creating gold test set for {dataset_name}")
#     print(f"{'='*60}")
    
#     # Read processed data
#     dataset_dir = os.path.join(data_path, dataset_name)
#     dataset_split_path = os.path.join(dataset_dir, f"{dataset_name}-final.json")
    
#     if not os.path.exists(dataset_split_path):
#         print(f"Warning: {dataset_split_path} not found. Skipping {dataset_name}.")
#         continue
    
#     processed_data = read_json_file(dataset_split_path)
#     print(f"Loaded processed data from: {dataset_split_path}")
    
#     # Create gold test set from test split
#     split_name = 'test'
#     test_samples = create_gold_test_set(processed_data, dataset_name, split_name, sample_count=500)
    
#     # Save gold test set
#     final_output_path = os.path.join(dataset_dir, f"{dataset_name}-gold-test.json")
#     save_json_file({'test': test_samples}, final_output_path)
    
#     print(f"\nGold test set saved to: {final_output_path}")
#     print(f"Test samples: {len(test_samples)}")

============================================================
Creating gold test set for DiscourseEE
============================================================
Reading JSON file from: /dartfs-hpc/rc/home/j/f006f3j/lab/omar/LoQA/Dataset/DiscourseEE/DiscourseEE-final.json
Loaded processed data from: /dartfs-hpc/rc/home/j/f006f3j/lab/omar/LoQA/Dataset/DiscourseEE/DiscourseEE-final.json

Total test samples available: 1883
Valid test samples: 874
Invalid test samples filtered out: 1009
Total unique documents in test split: 99

Randomly selecting 500 samples from test split for gold set...
Selected 500 samples from 97 unique documents (out of 99 total documents)
Data saved to: /dartfs-hpc/rc/home/j/f006f3j/lab/omar/LoQA/Dataset/DiscourseEE/DiscourseEE-gold-test.json

Gold test set saved to: /dartfs-hpc/rc/home/j/f006f3j/lab/omar/LoQA/Dataset/DiscourseEE/DiscourseEE-gold-test.json
Test samples: 500

============================================================
Creating gold test set for PHEE
============================================================
Reading JSON file from: /dartfs-hpc/rc/home/j/f006f3j/lab/omar/LoQA/Dataset/PHEE/PHEE-final.json
Loaded processed data from: /dartfs-hpc/rc/home/j/f006f3j/lab/omar/LoQA/Dataset/PHEE/PHEE-final.json

Total test samples available: 14520
Valid test samples: 4528
Invalid test samples filtered out: 9992
Total unique documents in test split: 968

Randomly selecting 500 samples from test split for gold set...
Selected 500 samples from 405 unique documents (out of 968 total documents)
Data saved to: /dartfs-hpc/rc/home/j/f006f3j/lab/omar/LoQA/Dataset/PHEE/PHEE-gold-test.json

Gold test set saved to: /dartfs-hpc/rc/home/j/f006f3j/lab/omar/LoQA/Dataset/PHEE/PHEE-gold-test.json
Test samples: 500

============================================================
Creating gold test set for CaseReportBench
============================================================
Reading JSON file from: /dartfs-hpc/rc/home/j/f006f3j/lab/omar/LoQA/Dataset/CaseReportBench/CaseReportBench-final.json
Loaded processed data from: /dartfs-hpc/rc/home/j/f006f3j/lab/omar/LoQA/Dataset/CaseReportBench/CaseReportBench-final.json

Total test samples available: 500
Valid test samples: 500
Invalid test samples filtered out: 0
Total unique documents in test split: 137

Randomly selecting 500 samples from test split for gold set...
Selected 500 samples from 137 unique documents (out of 137 total documents)
Data saved to: /dartfs-hpc/rc/home/j/f006f3j/lab/omar/LoQA/Dataset/CaseReportBench/CaseReportBench-gold-test.json

Gold test set saved to: /dartfs-hpc/rc/home/j/f006f3j/lab/omar/LoQA/Dataset/CaseReportBench/CaseReportBench-gold-test.json
Test samples: 500

============================================================
Creating gold test set for MACCROBAT
============================================================
Reading JSON file from: /dartfs-hpc/rc/home/j/f006f3j/lab/omar/LoQA/Dataset/MACCROBAT/MACCROBAT-final.json
Loaded processed data from: /dartfs-hpc/rc/home/j/f006f3j/lab/omar/LoQA/Dataset/MACCROBAT/MACCROBAT-final.json

Total test samples available: 741
Valid test samples: 741
Invalid test samples filtered out: 0
Total unique documents in test split: 20

Randomly selecting 500 samples from test split for gold set...
Selected 500 samples from 20 unique documents (out of 20 total documents)
Data saved to: /dartfs-hpc/rc/home/j/f006f3j/lab/omar/LoQA/Dataset/MACCROBAT/MACCROBAT-gold-test.json

Gold test set saved to: /dartfs-hpc/rc/home/j/f006f3j/lab/omar/LoQA/Dataset/MACCROBAT/MACCROBAT-gold-test.json
Test samples: 500

## Macrobat Dataset Merging

In [ ]:
# # Load the processed data and save MACCROBAT dataset
# split_names = ["train", "dev", "test"]
# dataset_name = "MACCROBAT"
# data_path = '/dartfs-hpc/rc/home/j/f006f3j/lab/omar/LoQA/Dataset'

# dataset_dir = os.path.join(data_path, dataset_name)
# final_dataset = {}

# for split_name in split_names:
#     dataset_split_path = os.path.join(dataset_dir, f"{dataset_name}-{split_name}.json")

#     if not os.path.exists(dataset_split_path):
#         print(f"Warning: {dataset_split_path} not found. Skipping {split_name}.")
#         continue

#     final_dataset[split_name] = read_json_file(dataset_split_path)
#     print(f"Loaded {split_name}: {len(final_dataset[split_name])} samples")

# output_path = os.path.join(dataset_dir, f"{dataset_name}-final.json")
# save_json_file(final_dataset, output_path)
# print(f"\nMACCROBAT dataset saved to: {output_path}")
# print(f"Train: {len(final_dataset.get('train', []))} | Dev: {len(final_dataset.get('dev', []))} | Test: {len(final_dataset.get('test', []))}")

Reading JSON file from: /dartfs-hpc/rc/home/j/f006f3j/lab/omar/LoQA/Dataset/MACCROBAT/MACCROBAT-train.json
Loaded train: 5508 samples
Reading JSON file from: /dartfs-hpc/rc/home/j/f006f3j/lab/omar/LoQA/Dataset/MACCROBAT/MACCROBAT-dev.json
Loaded dev: 671 samples
Reading JSON file from: /dartfs-hpc/rc/home/j/f006f3j/lab/omar/LoQA/Dataset/MACCROBAT/MACCROBAT-test.json
Loaded test: 741 samples
Data saved to: /dartfs-hpc/rc/home/j/f006f3j/lab/omar/LoQA/Dataset/MACCROBAT/MACCROBAT-final.json

MACCROBAT dataset saved to: /dartfs-hpc/rc/home/j/f006f3j/lab/omar/LoQA/Dataset/MACCROBAT/MACCROBAT-final.json
Train: 5508 | Dev: 671 | Test: 741

## CaseReportBench Spit Creation

In [26]:
# def create_splits_casereportbench(processed_data, test_count=500):
#     """
#     Create new splits for CaseReportBench dataset.
    
#     Args:
#         processed_data: Dictionary with 'test' key (all data)
#         test_count: Number of samples for test set
    
#     Returns:
#         Dictionary with new 'train', 'dev', 'test' splits
#     """
#     doc_id_key = "pmcid"
    
#     # Get all samples
#     all_samples = processed_data.get('test', [])
#     print(f"\nTotal samples available: {len(all_samples)}")
    
#     # Filter valid samples only
#     valid_samples = filter_valid_samples(all_samples)
#     invalid_count = len(all_samples) - len(valid_samples)
#     print(f"Valid samples: {len(valid_samples)}")
#     print(f"Invalid samples filtered out: {invalid_count}")
    
#     # Calculate total unique documents
#     total_docs = set(sample.get(doc_id_key) for sample in valid_samples if sample.get(doc_id_key) is not None)
#     print(f"Total unique documents: {len(total_docs)}")
    
#     # Shuffle all valid samples
#     random.shuffle(valid_samples)
    
#     # Step 1: Randomly select test set (500 samples)
#     print(f"\nRandomly selecting {test_count} samples for test set...")
#     test_samples = valid_samples[:test_count]
#     remaining_samples = valid_samples[test_count:]
    
#     # Calculate document coverage for test
#     test_doc_ids = set(sample.get(doc_id_key) for sample in test_samples if sample.get(doc_id_key) is not None)
#     print(f"Test set: {len(test_samples)} samples from {len(test_doc_ids)} unique documents (out of {len(total_docs)} total documents)")
    
#     # Step 2: Remaining data split into train (80%) and dev (20%)
#     print(f"\nRemaining samples: {len(remaining_samples)}")
    
#     # Split: 80% train, 20% dev
#     train_size = int(len(remaining_samples) * 0.8)
#     train_samples = remaining_samples[:train_size]
#     dev_samples = remaining_samples[train_size:]
    
#     # Calculate unique documents covered for train and dev
#     train_doc_ids = set(sample.get(doc_id_key) for sample in train_samples if sample.get(doc_id_key) is not None)
#     dev_doc_ids = set(sample.get(doc_id_key) for sample in dev_samples if sample.get(doc_id_key) is not None)
    
#     print(f"Train set: {len(train_samples)} samples from {len(train_doc_ids)} unique documents (out of {len(total_docs)} total documents)")
#     print(f"Dev set: {len(dev_samples)} samples from {len(dev_doc_ids)} unique documents (out of {len(total_docs)} total documents)")
    
#     # Update serial numbers
#     for idx, sample in enumerate(test_samples, 1):
#         sample['serial-number'] = f"test-{idx}"
#     for idx, sample in enumerate(dev_samples, 1):
#         sample['serial-number'] = f"dev-{idx}"
#     for idx, sample in enumerate(train_samples, 1):
#         sample['serial-number'] = f"train-{idx}"
    
#     return {
#         'train': train_samples,
#         'dev': dev_samples,
#         'test': test_samples
#     }

# # Set random seed for reproducibility
# random.seed(42)
# data_path = '/dartfs-hpc/rc/home/j/f006f3j/lab/omar/LoQA/Dataset'
# # Process each dataset to create gold test sets
# datasets_to_process = ["CaseReportBench"]

# for dataset_name in datasets_to_process:
#     print(f"\n{'='*60}")
#     print(f"Creating splits for {dataset_name}")
#     print(f"{'='*60}")
    
#     # Read processed data
#     dataset_dir = os.path.join(data_path, dataset_name)
#     dataset_split_path = os.path.join(dataset_dir, f"{dataset_name}-processed.json")
    
#     if not os.path.exists(dataset_split_path):
#         print(f"Warning: {dataset_split_path} not found. Skipping {dataset_name}.")
#         continue
    
#     processed_data = read_json_file(dataset_split_path)
#     print(f"Loaded processed data from: {dataset_split_path}")
    
#     # Create gold test set from test split
#     new_splits = create_splits_casereportbench(processed_data, test_count=500)
    
#     # Save gold test set
#     final_output_path = os.path.join(dataset_dir, f"{dataset_name}-final.json")
#     save_json_file({'test': test_samples}, final_output_path)
    
#     print(f"Test samples: {len(test_samples)}")

============================================================
Creating splits for CaseReportBench
============================================================
Reading JSON file from: /dartfs-hpc/rc/home/j/f006f3j/lab/omar/LoQA/Dataset/CaseReportBench/CaseReportBench-processed.json
Loaded processed data from: /dartfs-hpc/rc/home/j/f006f3j/lab/omar/LoQA/Dataset/CaseReportBench/CaseReportBench-processed.json

Total samples available: 2484
Valid samples: 1320
Invalid samples filtered out: 1164
Total unique documents: 138

Randomly selecting 500 samples for test set...
Test set: 500 samples from 138 unique documents (out of 138 total documents)

Remaining samples: 820
Train set: 656 samples from 138 unique documents (out of 138 total documents)
Dev set: 164 samples from 97 unique documents (out of 138 total documents)
Data saved to: /dartfs-hpc/rc/home/j/f006f3j/lab/omar/LoQA/Dataset/CaseReportBench/CaseReportBench-final.json

Gold test set saved to: /dartfs-hpc/rc/home/j/f006f3j/lab/omar/LoQA/Dataset/CaseReportBench/CaseReportBench-final.json
Test samples: 500

## This will be useful in the future for creating train and dev samples

In [ ]:
# def is_valid_sample(sample):
#     """
#     Check if a sample is valid (has non-null, non-empty raw-initial-ground-truth).
    
#     Args:
#         sample: Sample dictionary
    
#     Returns:
#         True if sample is valid, False otherwise
#     """
#     arg_value = sample.get("raw-initial-ground-truth", None)
#     if arg_value is None:
#         return False
#     if isinstance(arg_value, (list, str)) and len(arg_value) == 0:
#         return False
#     if isinstance(arg_value, list) and len(arg_value) == 1 and arg_value[0] == "null":
#         return False
#     return True


# def filter_valid_samples(samples):
#     """
#     Filter out invalid samples (where raw-initial-ground-truth is None, empty, or "null").
    
#     Args:
#         samples: List of sample dictionaries
    
#     Returns:
#         List of valid samples
#     """
#     return [sample for sample in samples if is_valid_sample(sample)]


# def group_samples_by_document(samples, doc_id_key):
#     """
#     Group samples by document ID to maximize document coverage.
#     Only groups valid samples (filters out invalid ones).
    
#     Args:
#         samples: List of sample dictionaries
#         doc_id_key: Key to use for document identification ('doc_id', 'id', or 'pmcid')
    
#     Returns:
#         Dictionary mapping document IDs to lists of valid samples
#     """
#     doc_groups = defaultdict(list)
#     for sample in samples:
#         # Only group valid samples
#         if is_valid_sample(sample):
#             doc_id = sample.get(doc_id_key)
#             if doc_id is not None:
#                 doc_groups[doc_id].append(sample)
#     return doc_groups


# def select_samples_maximizing_document_coverage(doc_groups, target_count):
#     """
#     Select samples to maximize the number of unique documents covered.
    
#     Strategy:
#     1. Sort documents by number of samples (ascending) to prioritize documents with fewer samples
#     2. Iteratively add documents until we reach the target count
#     3. If we exceed target, randomly sample from the last document added
    
#     Args:
#         doc_groups: Dictionary mapping document IDs to lists of samples
#         target_count: Target number of samples to select
    
#     Returns:
#         Tuple of (selected_samples, selected_doc_ids, remaining_doc_groups)
#         where remaining_doc_groups has the selected samples removed
#     """
#     # Create a deep copy to avoid modifying original
#     remaining_doc_groups = {k: v.copy() for k, v in doc_groups.items()}
    
#     # Sort documents by number of samples (ascending)
#     sorted_docs = sorted(remaining_doc_groups.items(), key=lambda x: len(x[1]))
    
#     selected_samples = []
#     selected_doc_ids = set()
    
#     # First pass: add entire documents until we approach target
#     for doc_id, samples in sorted_docs:
#         if len(selected_samples) + len(samples) <= target_count:
#             selected_samples.extend(samples)
#             selected_doc_ids.add(doc_id)
#             # Remove all samples from this document
#             remaining_doc_groups[doc_id] = []
#         elif len(selected_samples) < target_count:
#             # We need some samples from this document but not all
#             remaining_needed = target_count - len(selected_samples)
#             # Randomly sample from this document (shuffle a copy to avoid modifying original)
#             samples_copy = samples.copy()
#             random.shuffle(samples_copy)
#             selected_samples.extend(samples_copy[:remaining_needed])
#             selected_doc_ids.add(doc_id)
#             # Remove selected samples from remaining
#             remaining_doc_groups[doc_id] = samples_copy[remaining_needed:]
#             break
    
#     # If we haven't reached target, add more documents
#     if len(selected_samples) < target_count:
#         sorted_docs = sorted(remaining_doc_groups.items(), key=lambda x: len(x[1]) if x[1] else 0)
#         for doc_id, samples in sorted_docs:
#             if not samples:  # Skip empty documents
#                 continue
#             if doc_id not in selected_doc_ids:
#                 remaining_needed = target_count - len(selected_samples)
#                 if remaining_needed <= 0:
#                     break
#                 # Add samples from this document (shuffle a copy to avoid modifying original)
#                 samples_copy = samples.copy()
#                 random.shuffle(samples_copy)
#                 num_to_take = min(remaining_needed, len(samples_copy))
#                 selected_samples.extend(samples_copy[:num_to_take])
#                 selected_doc_ids.add(doc_id)
#                 # Remove selected samples from remaining
#                 remaining_doc_groups[doc_id] = samples_copy[num_to_take:]
#                 if len(selected_samples) >= target_count:
#                     break
    
#     # Trim to exact target if we exceeded
#     if len(selected_samples) > target_count:
#         selected_samples = selected_samples[:target_count]
    
#     # Final validation: ensure all selected samples are valid
#     selected_samples = [s for s in selected_samples if is_valid_sample(s)]
    
#     # Clean up empty documents from remaining
#     remaining_doc_groups = {k: v for k, v in remaining_doc_groups.items() if v}
    
#     return selected_samples, selected_doc_ids, remaining_doc_groups


# def create_splits_discourseee_phee(processed_data, dataset_name, test_count=500, train_count=1500, dev_count=500):
#     """
#     Create new splits for DiscourseEE or PHEE datasets.
    
#     Args:
#         processed_data: Dictionary with 'train', 'dev', 'test' keys
#         dataset_name: Name of the dataset ('DiscourseEE' or 'PHEE')
#         test_count: Number of samples for test set
#         train_count: Number of samples for train set
#         dev_count: Number of samples for dev set
    
#     Returns:
#         Dictionary with new 'train', 'dev', 'test' splits
#     """
#     # Determine document ID key
#     if dataset_name == "DiscourseEE":
#         doc_id_key = "doc_id"
#     elif dataset_name == "PHEE":
#         doc_id_key = "id"
#     else:
#         raise ValueError(f"Unknown dataset: {dataset_name}")
    
#     # Process each split independently
#     new_splits = {}
    
#     # Process train split
#     if 'train' in processed_data:
#         train_samples_raw = processed_data['train']
#         print(f"\n{'='*60}")
#         print(f"Processing TRAIN split")
#         print(f"{'='*60}")
#         print(f"Total train samples available: {len(train_samples_raw)}")
        
#         # Filter valid samples
#         valid_train = filter_valid_samples(train_samples_raw)
#         invalid_train = len(train_samples_raw) - len(valid_train)
#         print(f"Valid train samples: {len(valid_train)}")
#         print(f"Invalid train samples filtered out: {invalid_train}")
        
#         # Calculate total unique documents in train split
#         total_train_docs = set(sample.get(doc_id_key) for sample in valid_train if sample.get(doc_id_key) is not None)
#         print(f"Total unique documents in train split: {len(total_train_docs)}")
        
#         # Randomly sample train samples
#         print(f"\nRandomly selecting {train_count} samples from TRAIN split...")
#         random.shuffle(valid_train)
#         train_samples = valid_train[:train_count]
        
#         # Calculate document coverage
#         train_doc_ids = set(sample.get(doc_id_key) for sample in train_samples if sample.get(doc_id_key) is not None)
#         print(f"Selected {len(train_samples)} train samples from {len(train_doc_ids)} unique documents (out of {len(total_train_docs)} total documents)")
#         new_splits['train'] = train_samples
#     else:
#         new_splits['train'] = []
    
#     # Process dev split
#     if 'dev' in processed_data:
#         dev_samples_raw = processed_data['dev']
#         print(f"\n{'='*60}")
#         print(f"Processing DEV split")
#         print(f"{'='*60}")
#         print(f"Total dev samples available: {len(dev_samples_raw)}")
        
#         # Filter valid samples
#         valid_dev = filter_valid_samples(dev_samples_raw)
#         invalid_dev = len(dev_samples_raw) - len(valid_dev)
#         print(f"Valid dev samples: {len(valid_dev)}")
#         print(f"Invalid dev samples filtered out: {invalid_dev}")
        
#         # Calculate total unique documents in dev split
#         total_dev_docs = set(sample.get(doc_id_key) for sample in valid_dev if sample.get(doc_id_key) is not None)
#         print(f"Total unique documents in dev split: {len(total_dev_docs)}")
        
#         # Randomly sample dev samples
#         print(f"\nRandomly selecting {dev_count} samples from DEV split...")
#         random.shuffle(valid_dev)
#         dev_samples = valid_dev[:dev_count]
        
#         # Calculate document coverage
#         dev_doc_ids = set(sample.get(doc_id_key) for sample in dev_samples if sample.get(doc_id_key) is not None)
#         print(f"Selected {len(dev_samples)} dev samples from {len(dev_doc_ids)} unique documents (out of {len(total_dev_docs)} total documents)")
#         new_splits['dev'] = dev_samples
#     else:
#         new_splits['dev'] = []
    
#     # Process test split
#     if 'test' in processed_data:
#         test_samples_raw = processed_data['test']
#         print(f"\n{'='*60}")
#         print(f"Processing TEST split")
#         print(f"{'='*60}")
#         print(f"Total test samples available: {len(test_samples_raw)}")
        
#         # Filter valid samples
#         valid_test = filter_valid_samples(test_samples_raw)
#         invalid_test = len(test_samples_raw) - len(valid_test)
#         print(f"Valid test samples: {len(valid_test)}")
#         print(f"Invalid test samples filtered out: {invalid_test}")
        
#         # Calculate total unique documents in test split
#         total_test_docs = set(sample.get(doc_id_key) for sample in valid_test if sample.get(doc_id_key) is not None)
#         print(f"Total unique documents in test split: {len(total_test_docs)}")
        
#         # Randomly sample test samples
#         print(f"\nRandomly selecting {test_count} samples from TEST split...")
#         random.shuffle(valid_test)
#         test_samples = valid_test[:test_count]
        
#         # Calculate document coverage
#         test_doc_ids = set(sample.get(doc_id_key) for sample in test_samples if sample.get(doc_id_key) is not None)
#         print(f"Selected {len(test_samples)} test samples from {len(test_doc_ids)} unique documents (out of {len(total_test_docs)} total documents)")
#         new_splits['test'] = test_samples
#     else:
#         new_splits['test'] = []
    
#     # Update serial numbers
#     for idx, sample in enumerate(new_splits.get('test', []), 1):
#         sample['serial-number'] = f"test-{idx}"
#     for idx, sample in enumerate(new_splits.get('dev', []), 1):
#         sample['serial-number'] = f"dev-{idx}"
#     for idx, sample in enumerate(new_splits.get('train', []), 1):
#         sample['serial-number'] = f"train-{idx}"
    
#     return new_splits


# def create_splits_casereportbench(processed_data, test_count=500):
#     """
#     Create new splits for CaseReportBench dataset.
    
#     Args:
#         processed_data: Dictionary with 'test' key (all data)
#         test_count: Number of samples for test set
    
#     Returns:
#         Dictionary with new 'train', 'dev', 'test' splits
#     """
#     doc_id_key = "pmcid"
    
#     # Get all samples
#     all_samples = processed_data.get('test', [])
#     print(f"\nTotal samples available: {len(all_samples)}")
    
#     # Filter valid samples only
#     valid_samples = filter_valid_samples(all_samples)
#     invalid_count = len(all_samples) - len(valid_samples)
#     print(f"Valid samples: {len(valid_samples)}")
#     print(f"Invalid samples filtered out: {invalid_count}")
    
#     # Calculate total unique documents
#     total_docs = set(sample.get(doc_id_key) for sample in valid_samples if sample.get(doc_id_key) is not None)
#     print(f"Total unique documents: {len(total_docs)}")
    
#     # Shuffle all valid samples
#     random.shuffle(valid_samples)
    
#     # Step 1: Randomly select test set (500 samples)
#     print(f"\nRandomly selecting {test_count} samples for test set...")
#     test_samples = valid_samples[:test_count]
#     remaining_samples = valid_samples[test_count:]
    
#     # Calculate document coverage for test
#     test_doc_ids = set(sample.get(doc_id_key) for sample in test_samples if sample.get(doc_id_key) is not None)
#     print(f"Test set: {len(test_samples)} samples from {len(test_doc_ids)} unique documents (out of {len(total_docs)} total documents)")
    
#     # Step 2: Remaining data split into train (80%) and dev (20%)
#     print(f"\nRemaining samples: {len(remaining_samples)}")
    
#     # Split: 80% train, 20% dev
#     train_size = int(len(remaining_samples) * 0.8)
#     train_samples = remaining_samples[:train_size]
#     dev_samples = remaining_samples[train_size:]
    
#     # Calculate unique documents covered for train and dev
#     train_doc_ids = set(sample.get(doc_id_key) for sample in train_samples if sample.get(doc_id_key) is not None)
#     dev_doc_ids = set(sample.get(doc_id_key) for sample in dev_samples if sample.get(doc_id_key) is not None)
    
#     print(f"Train set: {len(train_samples)} samples from {len(train_doc_ids)} unique documents (out of {len(total_docs)} total documents)")
#     print(f"Dev set: {len(dev_samples)} samples from {len(dev_doc_ids)} unique documents (out of {len(total_docs)} total documents)")
    
#     # Update serial numbers
#     for idx, sample in enumerate(test_samples, 1):
#         sample['serial-number'] = f"test-{idx}"
#     for idx, sample in enumerate(dev_samples, 1):
#         sample['serial-number'] = f"dev-{idx}"
#     for idx, sample in enumerate(train_samples, 1):
#         sample['serial-number'] = f"train-{idx}"
    
#     return {
#         'train': train_samples,
#         'dev': dev_samples,
#         'test': test_samples
#     }