## Score calculation of different models

## Scores on the dev Set

In [2]:
from pathlib import Path

import json
from pathlib import Path

import pandas as pd
from IPython.display import display

DATASETS = ["CaseReportBench", "PHEE", "DiscourseEE", "MACCROBAT"]
QG_Models = ["gpt-oss-120b"]
PD_Models = ["qwen3-4b", "qwen3-8b", "gpt-oss-120b", "gpt-5-mini-medium", "gemini-3.1-pro-high"]

OUTPUTS_SC_DIR = "/dartfs/rc/home/j/f006f3j/lab/omar/LoQA/Outputs/sc"

SETUPS = ["schema", "cot-schema", "dynamicQ", "loqa", "optimized_loqa"]
MODELS = PD_Models


def load_scores(dataset: str, setup: str, model: str):
    """Return (relaxed_f1, complex_f1) for a given config, or (None, None) if missing."""
    base_dir = Path(OUTPUTS_SC_DIR) / dataset

    # if setup in {"schema", "cot-schema"}:
    #     filename = f"{setup}-{model}-zs-v0-{dataset}-gold-test-{model}-zs-v0.json"
    # else:  # loqa / optimized_loqa: QG model is fixed to gpt-oss-120b
    qg_model = "gpt-oss-120b"
    filename = f"{setup}-{qg_model}-zs-v0-{dataset}-dev-{model}-zs-v0.json"

    path = base_dir / filename
    if not path.exists():
        return None, None

    with path.open("r") as f:
        data = json.load(f).get("overall", {})

    relaxed_f1 = data.get("relaxed-match-f1")
    complex_f1 = data.get("complex-match-f1")
    return relaxed_f1, complex_f1


for dataset in DATASETS:
    rows = []
    for setup in SETUPS:
        row = {"setup": setup}
        for model in MODELS:
            relaxed, complex_ = load_scores(dataset, setup, model)
            #row[(model, "relaxed-match-f1")] = relaxed
            row[(model, "complex-match-f1")] = complex_
        rows.append(row)

    df = pd.DataFrame(rows).set_index("setup")

    # Convert dict-style columns to a proper MultiIndex: (model, metric)
    df.columns = pd.MultiIndex.from_tuples(df.columns, names=["model", "metric"])

    print("-" * 100)
    print(dataset)
    display(df.round(2))

----------------------------------------------------------------------------------------------------
CaseReportBench

model,qwen3-4b,qwen3-8b,gpt-oss-120b,gpt-5-mini-medium,gemini-3.1-pro-high
metric,complex-match-f1,complex-match-f1,complex-match-f1,complex-match-f1,complex-match-f1
setup,,,,,
schema,62.37,61.61,75.28,70.97,78.33
cot-schema,62.84,57.45,73.86,67.90,77.23
dynamicQ,54.33,50.57,57.87,52.54,57.67
loqa,76.93,72.07,92.68,88.70,91.91
optimized_loqa,79.17,73.42,96.86,92.42,94.00

----------------------------------------------------------------------------------------------------
PHEE

model,qwen3-4b,qwen3-8b,gpt-oss-120b,gpt-5-mini-medium,gemini-3.1-pro-high
metric,complex-match-f1,complex-match-f1,complex-match-f1,complex-match-f1,complex-match-f1
setup,,,,,
schema,76.48,79.45,75.71,71.82,83.35
cot-schema,69.17,73.54,76.21,78.57,84.21
dynamicQ,49.33,47.51,50.98,52.93,79.45
loqa,82.47,83.52,86.27,84.42,89.44
optimized_loqa,82.25,84.76,94.32,89.80,90.61

----------------------------------------------------------------------------------------------------
DiscourseEE

model,qwen3-4b,qwen3-8b,gpt-oss-120b,gpt-5-mini-medium,gemini-3.1-pro-high
metric,complex-match-f1,complex-match-f1,complex-match-f1,complex-match-f1,complex-match-f1
setup,,,,,
schema,52.97,53.80,60.54,55.63,57.76
cot-schema,54.73,55.73,61.87,53.58,60.13
dynamicQ,42.15,41.31,43.52,41.03,40.29
loqa,60.04,61.17,72.20,61.20,67.34
optimized_loqa,65.49,64.83,82.54,64.64,69.02

----------------------------------------------------------------------------------------------------
MACCROBAT

model,qwen3-4b,qwen3-8b,gpt-oss-120b,gpt-5-mini-medium,gemini-3.1-pro-high
metric,complex-match-f1,complex-match-f1,complex-match-f1,complex-match-f1,complex-match-f1
setup,,,,,
schema,36.60,38.26,42.07,42.52,58.13
cot-schema,36.90,38.58,42.46,39.98,57.06
dynamicQ,30.47,31.28,30.49,29.31,38.26
loqa,49.36,56.26,74.88,64.07,83.55
optimized_loqa,57.27,66.54,91.11,74.55,91.26

## Scores on the Test Set

In [7]:
from pathlib import Path

import json
from pathlib import Path

import pandas as pd
from IPython.display import display

DATASETS = ["CaseReportBench", "PHEE", "DiscourseEE", "MACCROBAT"]
QG_Models = ["gpt-oss-120b"]
PD_Models = [ "qwen3-4b", "qwen3-8b", "gpt-oss-120b", "gpt-5-mini-medium", "gemini-3.1-pro-high"]

OUTPUTS_SC_DIR = "/dartfs/rc/home/j/f006f3j/lab/omar/LoQA/Outputs/sc"

SETUPS = ["schema", "cot-schema", "dynamicQ"] #, "loqa", "optimized_loqa"
MODELS = PD_Models


def load_scores(dataset: str, setup: str, model: str):
    """Return (relaxed_f1, complex_f1) for a given config, or (None, None) if missing."""
    base_dir = Path(OUTPUTS_SC_DIR) / dataset

    # if setup in {"schema", "cot-schema"}:
    #     filename = f"{setup}-{model}-zs-v0-{dataset}-gold-test-{model}-zs-v0.json"
    # else:  # loqa / optimized_loqa: QG model is fixed to gpt-oss-120b
    qg_model = "gpt-oss-120b"
    filename = f"{setup}-{qg_model}-zs-v0-{dataset}-test-{model}-zs-v0.json"

    path = base_dir / filename
    if not path.exists():
        return None, None

    with path.open("r") as f:
        data = json.load(f).get("overall", {})

    relaxed_f1 = data.get("relaxed-match-f1")
    complex_f1 = data.get("complex-match-f1")
    return relaxed_f1, complex_f1


for dataset in DATASETS:
    rows = []
    for setup in SETUPS:
        row = {"setup": setup}
        for model in MODELS:
            relaxed, complex_ = load_scores(dataset, setup, model)
            #row[(model, "relaxed-match-f1")] = relaxed
            row[(model, "complex-match-f1")] = complex_
        rows.append(row)

    df = pd.DataFrame(rows).set_index("setup")

    # Convert dict-style columns to a proper MultiIndex: (model, metric)
    df.columns = pd.MultiIndex.from_tuples(df.columns, names=["model", "metric"])

    print("-" * 100)
    print(dataset)
    display(df.round(2))

----------------------------------------------------------------------------------------------------
CaseReportBench

model,qwen3-4b,qwen3-8b,gpt-oss-120b,gpt-5-mini-medium,gemini-3.1-pro-high
metric,complex-match-f1,complex-match-f1,complex-match-f1,complex-match-f1,complex-match-f1
setup,,,,,
schema,60.29,60.17,73.40,69.03,78.17
cot-schema,57.98,58.24,73.92,66.33,76.32
dynamicQ,53.76,49.45,56.31,51.14,55.88

----------------------------------------------------------------------------------------------------
PHEE

model,qwen3-4b,qwen3-8b,gpt-oss-120b,gpt-5-mini-medium,gemini-3.1-pro-high
metric,complex-match-f1,complex-match-f1,complex-match-f1,complex-match-f1,complex-match-f1
setup,,,,,
schema,76.92,80.02,74.08,74.05,81.37
cot-schema,67.98,73.67,77.50,76.41,80.53
dynamicQ,48.57,44.87,49.40,49.81,77.35

----------------------------------------------------------------------------------------------------
DiscourseEE

model,qwen3-4b,qwen3-8b,gpt-oss-120b,gpt-5-mini-medium,gemini-3.1-pro-high
metric,complex-match-f1,complex-match-f1,complex-match-f1,complex-match-f1,complex-match-f1
setup,,,,,
schema,50.55,53.68,60.36,55.15,58.13
cot-schema,50.44,55.13,61.01,52.71,59.62
dynamicQ,41.66,40.52,44.60,41.59,38.83

----------------------------------------------------------------------------------------------------
MACCROBAT

model,qwen3-4b,qwen3-8b,gpt-oss-120b,gpt-5-mini-medium,gemini-3.1-pro-high
metric,complex-match-f1,complex-match-f1,complex-match-f1,complex-match-f1,complex-match-f1
setup,,,,,
schema,37.55,39.11,43.70,41.36,58.74
cot-schema,37.41,41.75,43.60,41.60,58.51
dynamicQ,32.49,32.51,33.31,32.90,39.18

## Question Generation (QG) model ablation

In [1]:
from pathlib import Path

import json
from pathlib import Path

import pandas as pd
from IPython.display import display

DATASETS = ["CaseReportBench", "PHEE", "DiscourseEE", "MACCROBAT"]
QG_Models = ["qwen3-4b", "qwen3-8b", "gpt-oss-120b", "gpt-5.2-high", "gemini-3.1-pro-high"]
PD_Models = ["qwen3-4b", "qwen3-8b", "gpt-oss-120b", "gpt-5-mini-medium", "gemini-3.1-pro-high"]

OUTPUTS_SC_DIR = "/dartfs/rc/home/j/f006f3j/lab/omar/LoQA/Outputs/sc"
SETUP = "loqa"  # LoQA only: rows = QG models, columns = PD models × relaxed/complex


def load_scores(dataset: str, setup: str, qg_model: str, pd_model: str):
    """Return (relaxed_f1, complex_f1) for a given config, or (None, None) if missing."""
    base_dir = Path(OUTPUTS_SC_DIR) / dataset
    filename = f"{setup}-{qg_model}-zs-v0-{dataset}-dev-{pd_model}-zs-v0.json"
    path = base_dir / filename
    if not path.exists():
        return None, None

    with path.open("r") as f:
        data = json.load(f).get("overall", {})

    relaxed_f1 = data.get("relaxed-match-f1")
    complex_f1 = data.get("complex-match-f1")
    return relaxed_f1, complex_f1


datasets_dfs = {}  # store for later plotting

for dataset in DATASETS:
    rows = []
    for qg_model in QG_Models:
        row = {"QG": qg_model}
        for pd_model in PD_Models:
            relaxed, complex_ = load_scores(dataset, SETUP, qg_model, pd_model)
            #row[(pd_model, "relaxed-match-f1")] = relaxed
            row[(pd_model, "complex-match-f1")] = complex_
        rows.append(row)

    df = pd.DataFrame(rows).set_index("QG")

    # Columns: MultiIndex (PD model, metric)
    df.columns = pd.MultiIndex.from_tuples(df.columns, names=["PD_model", "metric"])
    datasets_dfs[dataset] = df

    print("-" * 100)
    print(dataset, "(LoQA only: rows=QG, cols=PD × relaxed/complex)")
    display(df.round(2))

----------------------------------------------------------------------------------------------------
CaseReportBench (LoQA only: rows=QG, cols=PD × relaxed/complex)

PD_model,qwen3-4b,qwen3-8b,gpt-oss-120b,gpt-5-mini-medium,gemini-3.1-pro-high
metric,complex-match-f1,complex-match-f1,complex-match-f1,complex-match-f1,complex-match-f1
QG,,,,,
qwen3-4b,64.66,62.20,56.19,52.35,68.61
qwen3-8b,62.03,61.40,57.14,51.82,71.36
gpt-oss-120b,76.93,72.07,92.68,88.70,91.91
gpt-5.2-high,77.03,73.75,93.08,88.48,93.17
gemini-3.1-pro-high,69.28,68.45,90.36,81.29,89.82

----------------------------------------------------------------------------------------------------
PHEE (LoQA only: rows=QG, cols=PD × relaxed/complex)

PD_model,qwen3-4b,qwen3-8b,gpt-oss-120b,gpt-5-mini-medium,gemini-3.1-pro-high
metric,complex-match-f1,complex-match-f1,complex-match-f1,complex-match-f1,complex-match-f1
QG,,,,,
qwen3-4b,65.66,66.88,61.03,61.31,79.21
qwen3-8b,62.82,63.60,58.31,56.18,79.55
gpt-oss-120b,82.47,83.52,86.27,84.42,89.44
gpt-5.2-high,82.07,85.01,87.98,85.44,88.74
gemini-3.1-pro-high,80.15,84.64,86.74,86.73,87.40

----------------------------------------------------------------------------------------------------
DiscourseEE (LoQA only: rows=QG, cols=PD × relaxed/complex)

PD_model,qwen3-4b,qwen3-8b,gpt-oss-120b,gpt-5-mini-medium,gemini-3.1-pro-high
metric,complex-match-f1,complex-match-f1,complex-match-f1,complex-match-f1,complex-match-f1
QG,,,,,
qwen3-4b,51.16,50.31,46.95,44.16,48.99
qwen3-8b,49.00,50.39,48.47,44.25,47.00
gpt-oss-120b,60.04,61.17,72.20,61.20,67.34
gpt-5.2-high,62.99,61.34,75.46,62.17,66.87
gemini-3.1-pro-high,59.64,60.45,70.58,60.85,65.77

----------------------------------------------------------------------------------------------------
MACCROBAT (LoQA only: rows=QG, cols=PD × relaxed/complex)

PD_model,qwen3-4b,qwen3-8b,gpt-oss-120b,gpt-5-mini-medium,gemini-3.1-pro-high
metric,complex-match-f1,complex-match-f1,complex-match-f1,complex-match-f1,complex-match-f1
QG,,,,,
qwen3-4b,40.93,41.74,42.13,40.15,51.68
qwen3-8b,38.63,39.90,38.79,38.20,48.17
gpt-oss-120b,49.36,56.26,74.88,64.07,83.55
gpt-5.2-high,55.23,58.98,73.85,66.28,84.57
gemini-3.1-pro-high,47.80,51.46,62.45,57.82,79.68

In [2]:
# Average score per QG model across PD models and datasets
# Choose which metric to average
METRIC_AVG = "complex-match-f1"  # or "relaxed-match-f1"

avg_per_dataset = {}
for dataset, df in datasets_dfs.items():
    # df: index = QG model, columns = (PD_model, metric)
    df_metric = df.xs(METRIC_AVG, axis=1, level=1).astype(float)
    # mean over PD models for each QG
    avg_per_dataset[dataset] = df_metric.mean(axis=1)

# DataFrame: rows = QG models, columns = datasets
avg_df = pd.DataFrame(avg_per_dataset)
# Overall mean across all 4 datasets for each QG model
avg_df["overall_mean"] = avg_df.mean(axis=1)

print(f"Average {METRIC_AVG} per QG model (per dataset and overall across datasets):")
display(avg_df.round(2))

Average complex-match-f1 per QG model (per dataset and overall across datasets):

,CaseReportBench,PHEE,DiscourseEE,MACCROBAT,overall_mean
QG,,,,,
qwen3-4b,60.80,66.82,48.31,43.33,54.82
qwen3-8b,60.75,64.09,47.82,40.74,53.35
gpt-oss-120b,84.46,85.22,64.39,65.62,74.92
gpt-5.2-high,85.10,85.85,65.77,67.78,76.12
gemini-3.1-pro-high,79.84,85.13,63.46,59.84,72.07

## Old Figure code

In [7]:

from pathlib import Path
import json
import pandas as pd
import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt
import numpy as np

DATASETS = ["CaseReportBench", "PHEE", "DiscourseEE", "MACCROBAT"]
QG_Models = ["qwen3-4b", "qwen3-8b", "gpt-oss-120b", "gpt-5.2-high", "gemini-3.1-pro-high"]
PD_Models = ["qwen3-4b", "qwen3-8b", "gpt-oss-120b", "gpt-5-mini-medium", "gemini-3.1-pro-high"]

OUTPUTS_SC_DIR = "/dartfs/rc/home/j/f006f3j/lab/omar/LoQA/Outputs/sc"
SETUP = "loqa"
METRIC = "complex-match-f1"
SAVE_PATH = "/dartfs-hpc/rc/home/j/f006f3j/lab/omar/LoQA/Code/xDev/loqa_scores_palette.png"

# Display names for figure text
QG_DISPLAY_NAMES = {
    "qwen3-4b": "Qwen3-4B",
    "qwen3-8b": "Qwen3-8B",
    "gpt-oss-120b": "GPT-OSS-120B",
    "gpt-5.2-high": "GPT-5.2",
    "gemini-3.1-pro-high": "Gemini-3.1-Pro",
}
PD_DISPLAY_NAMES = {
    "qwen3-4b": "Qwen3-4B",
    "qwen3-8b": "Qwen3-8B",
    "gpt-oss-120b": "GPT-Oss-120B",
    "gpt-5-mini-medium": "GPT-5-Mini",
    "gemini-3.1-pro-high": "Gemini-3.1-Pro",
}
#X_AXIS_LABEL = "Question Generation Model"
Y_AXIS_LABEL = "F1 Score" if METRIC == "complex-match-f1" else "Relaxed Match F1 (%)"


def load_scores(dataset: str, setup: str, qg_model: str, pd_model: str):
    base_dir = Path(OUTPUTS_SC_DIR) / dataset
    filename = f"{setup}-{qg_model}-zs-v0-{dataset}-dev-{pd_model}-zs-v0.json"
    path = base_dir / filename
    if not path.exists():
        return None, None

    with path.open("r") as f:
        data = json.load(f).get("overall", {})

    relaxed_f1 = data.get("relaxed-match-f1")
    complex_f1 = data.get("complex-match-f1")
    return relaxed_f1, complex_f1


datasets_dfs = {}
for dataset in DATASETS:
    rows = []
    for qg_model in QG_Models:
        row = {"QG": qg_model}
        for pd_model in PD_Models:
            relaxed, complex_ = load_scores(dataset, SETUP, qg_model, pd_model)
            row[(pd_model, "relaxed-match-f1")] = relaxed
            row[(pd_model, "complex-match-f1")] = complex_
        rows.append(row)

    df = pd.DataFrame(rows).set_index("QG")
    df.columns = pd.MultiIndex.from_tuples(df.columns, names=["PD_model", "metric"])
    datasets_dfs[dataset] = df

PD_COLOR_MAP = {
    "qwen3-4b": "#0072B2",
    "qwen3-8b": "#E69F00",
    "gpt-oss-120b": "#009E73",
    "gpt-5-mini-medium": "#D55E00",
    "gemini-3.1-pro-high": "#7A7A7A"
}
PD_HATCH_MAP = {
    "qwen3-4b": "",
    "qwen3-8b": "//",
    "gpt-oss-120b": "\\\\",
    "gpt-5-mini-medium": "-",
    "gemini-3.1-pro-high": "..",
}

plt.rcParams["figure.dpi"] = 1200
plt.rcParams["savefig.dpi"] = 1200
plt.rcParams["pdf.fonttype"] = 42
plt.rcParams["ps.fonttype"] = 42
plt.rcParams["font.family"] = "DejaVu Sans"

fig, axes = plt.subplots(2, 2, figsize=(12, 8), sharey=True)
axes = axes.flatten()

handles_legend = None
for ax, dataset in zip(axes, DATASETS):
    df = datasets_dfs[dataset]
    df_plot = df.xs(METRIC, axis=1, level=1).astype(float)

    x = np.arange(len(QG_Models))
    width = 0.8 / len(PD_Models)

    for i, pd_model in enumerate(PD_Models):
        offset = (i - len(PD_Models) / 2 + 0.5) * width
        vals = df_plot[pd_model].values

        bars = ax.bar(
            x + offset,
            vals,
            width,
            label=PD_DISPLAY_NAMES.get(pd_model, pd_model),
            color=PD_COLOR_MAP[pd_model],
            edgecolor="black",
            linewidth=0.7,
            hatch=PD_HATCH_MAP[pd_model],
            alpha=0.95,
        )

    if handles_legend is None:
        handles_legend, labels_legend = ax.get_legend_handles_labels()

    ax.set_xticks(x)
    ax.set_xticklabels([QG_DISPLAY_NAMES.get(m, m) for m in QG_Models], rotation=20, ha="right")
    # ax.set_xlabel(X_AXIS_LABEL)
    ax.set_ylabel(Y_AXIS_LABEL)
    ax.set_title(dataset, fontsize=12, fontweight="bold", fontstyle="italic")
    ax.set_ylim(0, 105)
    ax.grid(axis="y", alpha=0.2, linewidth=0.6)
    ax.spines["top"].set_visible(False)
    ax.spines["right"].set_visible(False)

fig.legend(
    handles_legend,
    labels_legend,
    loc="upper center",
    bbox_to_anchor=(0.5, 1.0),
    ncol=len(PD_Models),
    frameon=True,
    fontsize=9,
    columnspacing=1.2,
)
# BOTTOM_TITLE = "Question Generation Model Ablation: QG Models (X-axis) vs Prediction Models (Y-axis)"
# fig.text(0.5, 0.005, BOTTOM_TITLE, ha="center", va="bottom", fontsize=11, fontweight="bold")
# plt.tight_layout(rect=[0, 0.06, 1, 0.93])  # leaves room at bottom + top


plt.tight_layout(rect=[0, 0.02, 1, 0.93])
fig.savefig(SAVE_PATH, bbox_inches="tight")
print(SAVE_PATH)

/dartfs-hpc/rc/home/j/f006f3j/lab/omar/LoQA/Code/xDev/loqa_scores_palette.png

## All QG Model Performance on Test set with DynamicQ

In [1]:
from pathlib import Path
import json
import pandas as pd
from IPython.display import display

DATASETS = ["CaseReportBench", "PHEE", "DiscourseEE", "MACCROBAT"]
QG_Models = ["qwen3-4b", "qwen3-8b", "gpt-oss-120b", "gpt-5.2-high", "gemini-3.1-pro-high"]
PD_Models = [ "qwen3-4b", "qwen3-8b", "gpt-oss-120b", "gpt-5-mini-medium", "gemini-3.1-pro-high"]

OUTPUTS_SC_DIR = "/dartfs/rc/home/j/f006f3j/lab/omar/LoQA/Outputs/sc"
SETUP = "dynamicQ"


def load_scores(dataset: str, setup: str, model: str, qg_model: str):
    base_dir = Path(OUTPUTS_SC_DIR) / dataset
    filename = f"{setup}-{qg_model}-zs-v0-{dataset}-test-{model}-zs-v0.json"
    path = base_dir / filename
    if not path.exists():
        return None, None
    with path.open("r") as f:
        data = json.load(f).get("overall", {})
    return data.get("relaxed-match-f1"), data.get("complex-match-f1")


for dataset in DATASETS:
    rows = []
    for qg_model in QG_Models:
        row = {"QG Model": qg_model}
        for pd_model in PD_Models:
            relaxed, complex_ = load_scores(dataset, SETUP, pd_model, qg_model)
            #row[(pd_model, "R-F1")] = relaxed
            row[(pd_model, "C-F1")] = complex_
        rows.append(row)

    df = pd.DataFrame(rows).set_index("QG Model")
    df.columns = pd.MultiIndex.from_tuples(df.columns, names=["PD Model", "Metric"])

    print("-" * 100)
    print(dataset)
    display(df.round(2))

----------------------------------------------------------------------------------------------------
CaseReportBench

PD Model,qwen3-4b,qwen3-8b,gpt-oss-120b,gpt-5-mini-medium,gemini-3.1-pro-high
Metric,C-F1,C-F1,C-F1,C-F1,C-F1
QG Model,,,,,
qwen3-4b,63.18,59.26,52.28,45.73,66.14
qwen3-8b,63.26,60.51,56.67,49.71,67.33
gpt-oss-120b,53.76,49.45,56.31,51.14,55.88
gpt-5.2-high,60.46,58.07,69.36,64.13,65.63
gemini-3.1-pro-high,62.01,59.39,70.21,67.04,71.26

----------------------------------------------------------------------------------------------------
PHEE

PD Model,qwen3-4b,qwen3-8b,gpt-oss-120b,gpt-5-mini-medium,gemini-3.1-pro-high
Metric,C-F1,C-F1,C-F1,C-F1,C-F1
QG Model,,,,,
qwen3-4b,64.71,63.54,62.30,58.75,79.89
qwen3-8b,62.10,63.26,58.58,55.42,79.11
gpt-oss-120b,48.57,44.87,49.40,49.81,77.35
gpt-5.2-high,62.59,61.39,71.87,71.44,80.33
gemini-3.1-pro-high,79.39,80.68,80.98,80.13,81.89

----------------------------------------------------------------------------------------------------
DiscourseEE

PD Model,qwen3-4b,qwen3-8b,gpt-oss-120b,gpt-5-mini-medium,gemini-3.1-pro-high
Metric,C-F1,C-F1,C-F1,C-F1,C-F1
QG Model,,,,,
qwen3-4b,50.11,48.75,47.13,44.96,47.64
qwen3-8b,47.91,48.90,46.59,42.66,44.36
gpt-oss-120b,41.66,40.52,44.60,41.59,38.83
gpt-5.2-high,48.89,43.95,50.55,46.65,41.04
gemini-3.1-pro-high,51.39,49.65,53.18,50.84,49.52

----------------------------------------------------------------------------------------------------
MACCROBAT

PD Model,qwen3-4b,qwen3-8b,gpt-oss-120b,gpt-5-mini-medium,gemini-3.1-pro-high
Metric,C-F1,C-F1,C-F1,C-F1,C-F1
QG Model,,,,,
qwen3-4b,38.02,41.50,41.07,38.72,48.43
qwen3-8b,38.71,40.28,40.12,39.07,47.57
gpt-oss-120b,32.49,32.51,33.31,32.90,39.18
gpt-5.2-high,39.57,39.88,40.50,39.30,42.91
gemini-3.1-pro-high,37.13,40.59,43.25,41.49,52.13

## Fine-tuned Model performance on test set

In [10]:
from pathlib import Path
import json
import pandas as pd
from IPython.display import display

DATASETS = ["CaseReportBench", "PHEE", "DiscourseEE", "MACCROBAT"]
QG_Models = [ 'qwen3-4b-mix-balanced-v1', 'qwen3-4b-mix-high-v1','qwen3-8b-mix-bln-v5', 'qwen3-8b-mix-high-v1']
PD_Models = [ "qwen3-4b", "qwen3-8b", "gpt-oss-120b", "gpt-5-mini-medium", "gemini-3.1-pro-high"]

OUTPUTS_SC_DIR = "/dartfs/rc/home/j/f006f3j/lab/omar/LoQA/Outputs/ft_outputs/sc"
SETUP = "ft"


def load_scores(dataset: str, setup: str, model: str, qg_model: str):
    base_dir = Path(OUTPUTS_SC_DIR) / dataset
    filename = f"{setup}-{qg_model}-zs-v0-{dataset}-test-{model}-zs-v0.json"
    path = base_dir / filename
    if not path.exists():
        return None, None
    with path.open("r") as f:
        data = json.load(f).get("overall", {})
    return data.get("relaxed-match-f1"), data.get("complex-match-f1")


for dataset in DATASETS:
    rows = []
    for qg_model in QG_Models:
        row = {"QG Model": qg_model}
        for pd_model in PD_Models:
            relaxed, complex_ = load_scores(dataset, SETUP, pd_model, qg_model)
            #row[(pd_model, "R-F1")] = relaxed
            row[(pd_model, "C-F1")] = complex_
        rows.append(row)

    df = pd.DataFrame(rows).set_index("QG Model")
    df.columns = pd.MultiIndex.from_tuples(df.columns, names=["PD Model", "Metric"])

    print("-" * 100)
    print(dataset)
    display(df.round(2))

----------------------------------------------------------------------------------------------------
CaseReportBench

PD Model,qwen3-4b,qwen3-8b,gpt-oss-120b,gpt-5-mini-medium,gemini-3.1-pro-high
Metric,C-F1,C-F1,C-F1,C-F1,C-F1
QG Model,,,,,
qwen3-4b-mix-balanced-v1,60.64,59.43,60.68,62.17,60.95
qwen3-4b-mix-high-v1,62.56,64.09,71.63,67.86,71.32
qwen3-8b-mix-bln-v5,62.98,61.59,69.40,66.07,67.89
qwen3-8b-mix-high-v1,60.89,61.03,69.22,65.64,66.83

----------------------------------------------------------------------------------------------------
PHEE

PD Model,qwen3-4b,qwen3-8b,gpt-oss-120b,gpt-5-mini-medium,gemini-3.1-pro-high
Metric,C-F1,C-F1,C-F1,C-F1,C-F1
QG Model,,,,,
qwen3-4b-mix-balanced-v1,75.76,78.60,79.89,79.69,82.20
qwen3-4b-mix-high-v1,78.22,81.52,81.00,78.97,83.92
qwen3-8b-mix-bln-v5,77.42,77.38,78.88,77.18,81.35
qwen3-8b-mix-high-v1,78.07,80.66,82.36,82.74,84.25

----------------------------------------------------------------------------------------------------
DiscourseEE

PD Model,qwen3-4b,qwen3-8b,gpt-oss-120b,gpt-5-mini-medium,gemini-3.1-pro-high
Metric,C-F1,C-F1,C-F1,C-F1,C-F1
QG Model,,,,,
qwen3-4b-mix-balanced-v1,45.27,47.61,49.36,50.38,46.22
qwen3-4b-mix-high-v1,49.75,50.16,54.12,54.01,51.46
qwen3-8b-mix-bln-v5,47.11,49.20,56.74,54.47,52.71
qwen3-8b-mix-high-v1,47.72,50.57,55.66,53.21,50.21

----------------------------------------------------------------------------------------------------
MACCROBAT

PD Model,qwen3-4b,qwen3-8b,gpt-oss-120b,gpt-5-mini-medium,gemini-3.1-pro-high
Metric,C-F1,C-F1,C-F1,C-F1,C-F1
QG Model,,,,,
qwen3-4b-mix-balanced-v1,40.61,45.22,49.52,45.45,53.18
qwen3-4b-mix-high-v1,41.71,46.37,51.39,48.62,56.84
qwen3-8b-mix-bln-v5,41.81,44.96,50.64,46.24,56.22
qwen3-8b-mix-high-v1,41.02,43.25,50.96,47.53,53.36

## Fine-tuned model performance on the dev set

In [5]:
from pathlib import Path
import json
import pandas as pd
from IPython.display import display

DATASETS = ["CaseReportBench", "PHEE", "DiscourseEE", "MACCROBAT"]
QG_Models = [ 'qwen3-4b-mix-balanced-v1', 'qwen3-4b-mix-high-v1','qwen3-8b-mix-bln-v5', 'qwen3-8b-mix-high-v1']
PD_Models = ["gpt-oss-120b", "qwen3-4b", "qwen3-8b", "gpt-5-mini-medium", "gemini-3.1-pro-high"]

OUTPUTS_SC_DIR = "/dartfs/rc/home/j/f006f3j/lab/omar/LoQA/Outputs/ft_outputs/sc"
SETUP = "ft"


def load_scores(dataset: str, setup: str, model: str, qg_model: str):
    base_dir = Path(OUTPUTS_SC_DIR) / dataset
    filename = f"{setup}-{qg_model}-zs-v0-{dataset}-dev-{model}-zs-v0.json"
    path = base_dir / filename
    if not path.exists():
        return None, None
    with path.open("r") as f:
        data = json.load(f).get("overall", {})
    return data.get("relaxed-match-f1"), data.get("complex-match-f1")


for dataset in DATASETS:
    rows = []
    for qg_model in QG_Models:
        row = {"QG Model": qg_model}
        for pd_model in PD_Models:
            relaxed, complex_ = load_scores(dataset, SETUP, pd_model, qg_model)
            #row[(pd_model, "R-F1")] = relaxed
            row[(pd_model, "C-F1")] = complex_
        rows.append(row)

    df = pd.DataFrame(rows).set_index("QG Model")
    df.columns = pd.MultiIndex.from_tuples(df.columns, names=["PD Model", "Metric"])

    print("-" * 100)
    print(dataset)
    display(df.round(2))

----------------------------------------------------------------------------------------------------
CaseReportBench

PD Model,gpt-oss-120b,qwen3-4b,qwen3-8b,gpt-5-mini-medium,gemini-3.1-pro-high
Metric,C-F1,C-F1,C-F1,C-F1,C-F1
QG Model,,,,,
qwen3-4b-mix-balanced-v1,63.18,61.31,63.59,None,None
qwen3-4b-mix-high-v1,71.55,66.35,66.79,None,None
qwen3-8b-mix-bln-v5,69.71,63.73,63.62,None,None
qwen3-8b-mix-high-v1,68.93,63.11,62.72,None,None

----------------------------------------------------------------------------------------------------
PHEE

PD Model,gpt-oss-120b,qwen3-4b,qwen3-8b,gpt-5-mini-medium,gemini-3.1-pro-high
Metric,C-F1,C-F1,C-F1,C-F1,C-F1
QG Model,,,,,
qwen3-4b-mix-balanced-v1,79.24,78.38,80.05,None,None
qwen3-4b-mix-high-v1,79.76,79.53,79.92,None,None
qwen3-8b-mix-bln-v5,80.73,77.18,79.96,None,None
qwen3-8b-mix-high-v1,82.41,79.21,81.39,None,None

----------------------------------------------------------------------------------------------------
DiscourseEE

PD Model,gpt-oss-120b,qwen3-4b,qwen3-8b,gpt-5-mini-medium,gemini-3.1-pro-high
Metric,C-F1,C-F1,C-F1,C-F1,C-F1
QG Model,,,,,
qwen3-4b-mix-balanced-v1,53.07,50.03,48.61,None,None
qwen3-4b-mix-high-v1,53.08,51.69,51.91,None,None
qwen3-8b-mix-bln-v5,57.96,51.12,50.93,None,None
qwen3-8b-mix-high-v1,55.62,50.33,52.07,None,None

----------------------------------------------------------------------------------------------------
MACCROBAT

PD Model,gpt-oss-120b,qwen3-4b,qwen3-8b,gpt-5-mini-medium,gemini-3.1-pro-high
Metric,C-F1,C-F1,C-F1,C-F1,C-F1
QG Model,,,,,
qwen3-4b-mix-balanced-v1,48.45,40.47,42.02,None,None
qwen3-4b-mix-high-v1,50.00,41.36,45.22,None,None
qwen3-8b-mix-bln-v5,49.05,39.08,41.28,None,None
qwen3-8b-mix-high-v1,53.38,41.71,45.27,None,None

## In-domain fine-tuned results on each dataset

In [19]:
from pathlib import Path
import json
import pandas as pd
from IPython.display import display

DATASETS = ["CaseReportBench", "PHEE", "DiscourseEE", "MACCROBAT"]
QG_Models = [ 'qwen3-4b', 'qwen3-8b']
PD_Models = [ "qwen3-4b", "qwen3-8b", "gpt-oss-120b", "gpt-5-mini-medium", "gemini-3.1-pro-high"]

OUTPUTS_SC_DIR = "/dartfs/rc/home/j/f006f3j/lab/omar/LoQA/Outputs/ft_outputs/sc"
SETUP = "ft"


def load_scores(dataset: str, setup: str, model: str, qg_model: str):
    base_dir = Path(OUTPUTS_SC_DIR) / dataset
    filename = f"{setup}-{qg_model}-zs-v0-{dataset}-test-{model}-zs-v0.json"
    #print(filename)
    path = base_dir / filename
    if not path.exists():
        return None, None
    with path.open("r") as f:
        data = json.load(f).get("overall", {})
    return data.get("relaxed-match-f1"), data.get("complex-match-f1")


for dataset in DATASETS:
    rows = []
    for model in QG_Models:
        qg_model =f'{model}-{dataset}-v1'
        row = {"QG Model": qg_model}
        for pd_model in PD_Models:
            relaxed, complex_ = load_scores(dataset, SETUP, pd_model, qg_model)
            #row[(pd_model, "R-F1")] = relaxed
            row[(pd_model, "C-F1")] = complex_
        rows.append(row)

    df = pd.DataFrame(rows).set_index("QG Model")
    df.columns = pd.MultiIndex.from_tuples(df.columns, names=["PD Model", "Metric"])

    print("-" * 100)
    print(dataset)
    display(df.round(2))

----------------------------------------------------------------------------------------------------
CaseReportBench

PD Model,qwen3-4b,qwen3-8b,gpt-oss-120b,gpt-5-mini-medium,gemini-3.1-pro-high
Metric,C-F1,C-F1,C-F1,C-F1,C-F1
QG Model,,,,,
qwen3-4b-CaseReportBench-v1,58.98,60.01,63.15,61.59,60.77
qwen3-8b-CaseReportBench-v1,63.85,64.59,70.88,69.16,69.98

----------------------------------------------------------------------------------------------------
PHEE

PD Model,qwen3-4b,qwen3-8b,gpt-oss-120b,gpt-5-mini-medium,gemini-3.1-pro-high
Metric,C-F1,C-F1,C-F1,C-F1,C-F1
QG Model,,,,,
qwen3-4b-PHEE-v1,78.48,80.24,83.61,80.30,84.96
qwen3-8b-PHEE-v1,77.86,79.99,84.52,80.03,83.70

----------------------------------------------------------------------------------------------------
DiscourseEE

PD Model,qwen3-4b,qwen3-8b,gpt-oss-120b,gpt-5-mini-medium,gemini-3.1-pro-high
Metric,C-F1,C-F1,C-F1,C-F1,C-F1
QG Model,,,,,
qwen3-4b-DiscourseEE-v1,47.69,48.57,51.35,51.88,45.96
qwen3-8b-DiscourseEE-v1,47.93,47.63,50.86,53.37,48.73

----------------------------------------------------------------------------------------------------
MACCROBAT

PD Model,qwen3-4b,qwen3-8b,gpt-oss-120b,gpt-5-mini-medium,gemini-3.1-pro-high
Metric,C-F1,C-F1,C-F1,C-F1,C-F1
QG Model,,,,,
qwen3-4b-MACCROBAT-v1,45.37,45.97,49.2,46.54,55.34
qwen3-8b-MACCROBAT-v1,40.95,44.69,50.9,45.45,56.74

## Out-of-domain results with Qwen3-4B,Qwen3-8B fine-tuned models

In [1]:
from pathlib import Path
import json
import pandas as pd
from IPython.display import display

DATASETS = ["GENEVA", "DocEE"]
QG_Models = ['qwen3-4b-mix-balanced-v1', 'qwen3-4b-mix-high-v1',  'qwen3-8b-mix-balanced-v5', 'qwen3-8b-mix-high-v1']
PD_Models = [ "qwen3-4b", "qwen3-8b", "gpt-oss-120b", "gpt-5-mini-medium", "gemini-3.1-pro-high"]

OUTPUTS_SC_DIR = "/dartfs/rc/home/j/f006f3j/lab/omar/LoQA/Outputs/ft_outputs/sc"
SETUP = "ft"


def load_scores(dataset: str, setup: str, model: str, qg_model: str):
    base_dir = Path(OUTPUTS_SC_DIR) / dataset
    filename = f"{setup}-{qg_model}-zs-v0-{dataset}-test-{model}-zs-v0.json"
    path = base_dir / filename
    if not path.exists():
        return None, None
    with path.open("r") as f:
        data = json.load(f).get("overall", {})
    return data.get("relaxed-match-f1"), data.get("complex-match-f1")


for dataset in DATASETS:
    rows = []
    for qg_model in QG_Models:
        row = {"QG Model": qg_model}
        for pd_model in PD_Models:
            relaxed, complex_ = load_scores(dataset, SETUP, pd_model, qg_model)
            #row[(pd_model, "R-F1")] = relaxed
            row[(pd_model, "C-F1")] = complex_
        rows.append(row)

    df = pd.DataFrame(rows).set_index("QG Model")
    df.columns = pd.MultiIndex.from_tuples(df.columns, names=["PD Model", "Metric"])

    print("-" * 100)
    print(dataset)
    display(df.round(2))

----------------------------------------------------------------------------------------------------
GENEVA

PD Model,qwen3-4b,qwen3-8b,gpt-oss-120b,gpt-5-mini-medium,gemini-3.1-pro-high
Metric,C-F1,C-F1,C-F1,C-F1,C-F1
QG Model,,,,,
qwen3-4b-mix-balanced-v1,48.79,47.30,47.30,49.52,63.43
qwen3-4b-mix-high-v1,48.18,52.21,48.87,52.86,61.96
qwen3-8b-mix-balanced-v5,50.59,49.56,47.47,50.44,66.35
qwen3-8b-mix-high-v1,49.11,49.51,47.01,50.21,64.18

----------------------------------------------------------------------------------------------------
DocEE

PD Model,qwen3-4b,qwen3-8b,gpt-oss-120b,gpt-5-mini-medium,gemini-3.1-pro-high
Metric,C-F1,C-F1,C-F1,C-F1,C-F1
QG Model,,,,,
qwen3-4b-mix-balanced-v1,59.42,51.29,51.92,55.38,53.90
qwen3-4b-mix-high-v1,57.98,51.63,55.01,57.80,53.97
qwen3-8b-mix-balanced-v5,59.27,52.50,56.22,58.63,56.61
qwen3-8b-mix-high-v1,54.04,50.04,51.96,56.63,55.46

## Out-of-domain performance with non-fine tuned models

In [2]:
from pathlib import Path
import json
import pandas as pd
from IPython.display import display

DATASETS = ["GENEVA", "DocEE"]
QG_Models = ['qwen3-4b', 'qwen3-8b']
PD_Models = ["qwen3-4b", "qwen3-8b", "gpt-oss-120b", "gpt-5-mini-medium", "gemini-3.1-pro-high"]

OUTPUTS_SC_DIR = "/dartfs/rc/home/j/f006f3j/lab/omar/LoQA/Outputs/sc"
SETUP = "dynamicQ"


def load_scores(dataset: str, setup: str, model: str, qg_model: str):
    base_dir = Path(OUTPUTS_SC_DIR) / dataset
    filename = f"{setup}-{qg_model}-zs-v0-{dataset}-test-{model}-zs-v0.json"
    path = base_dir / filename
    if not path.exists():
        return None, None
    with path.open("r") as f:
        data = json.load(f).get("overall", {})
    return data.get("relaxed-match-f1"), data.get("complex-match-f1")


for dataset in DATASETS:
    rows = []
    for qg_model in QG_Models:
        row = {"QG Model": qg_model}
        for pd_model in PD_Models:
            relaxed, complex_ = load_scores(dataset, SETUP, pd_model, qg_model)
            #row[(pd_model, "R-F1")] = relaxed
            row[(pd_model, "C-F1")] = complex_
        rows.append(row)

    df = pd.DataFrame(rows).set_index("QG Model")
    df.columns = pd.MultiIndex.from_tuples(df.columns, names=["PD Model", "Metric"])

    print("-" * 100)
    print(dataset)
    display(df.round(2))

----------------------------------------------------------------------------------------------------
GENEVA

PD Model qwen3-4b qwen3-8b gpt-oss-120b gpt-5-mini-medium gemini-3.1-pro-high
Metric       C-F1     C-F1         C-F1              C-F1                C-F1
QG Model
qwen3-4b    55.37    54.55        54.36             54.57               76.79
qwen3-8b    54.07    51.26        53.93             53.46               78.76

----------------------------------------------------------------------------------------------------
DocEE

PD Model qwen3-4b qwen3-8b gpt-oss-120b gpt-5-mini-medium gemini-3.1-pro-high
Metric       C-F1     C-F1         C-F1              C-F1                C-F1
QG Model
qwen3-4b    56.94    48.23        36.00             36.05               55.41
qwen3-8b    58.26    50.44        41.22             40.82               55.28

In [ ]:
# import matplotlib.pyplot as plt
# import numpy as np

# # --- Customise here ---
# PALETTE = "tab10"   # options: "tab10", "Set3", "Paired", "viridis", "plasma", "tab20", "Pastel1", etc.
# METRIC = "complex-match-f1"  # or "relaxed-match-f1"
# # Download: set SAVE_PATH to a file path to save; set SAVE_DPI for resolution (e.g. 150, 300, 600)
# SAVE_PATH = "/dartfs-hpc/rc/home/j/f006f3j/lab/omar/LoQA/loq"      # e.g. "loqa_scores.png" or "/path/to/figure.pdf"
# SAVE_DPI = 600      # used only when SAVE_PATH is set

# # Bar appearance (one value per PD model, or single value for all)
# BAR_EDGE_COLOR = "gray"    # bar outline: "white", "black", "gray", or (r,g,b)
# BAR_EDGE_WIDTH = 0.6       # outline thickness (0 = no outline)
# BAR_ALPHA = 1.0            # fill opacity 0–1
# # Hatch: None = no hatch; or list of patterns (one per PD model): "", "/", "\\", "|", "-", "+", "x", "o", "O", ".", "*"
# BAR_HATCH = ["", "/", "\\", "|", "-", "+"]        # e.g. ["", "/", "\\", "|", "-", "+"]  or  ["", "///", "\\\\", "---"]

# # High-quality figure settings
# plt.rcParams["figure.dpi"] = 600
# plt.rcParams["font.family"] = "sans-serif"
# plt.rcParams["font.size"] = 10
# plt.rcParams["axes.titlesize"] = 12
# plt.rcParams["axes.labelsize"] = 10

# fig, axes = plt.subplots(2, 2, figsize=(12, 8), sharey=True)
# axes = axes.flatten()

# # Colours from chosen palette (avoid very light/dark ends for qualitative palettes)
# cmap = plt.get_cmap(PALETTE)
# colors = cmap(np.linspace(0.15, 0.85, len(PD_Models))) if PALETTE in ("viridis", "plasma", "inferno", "magma", "cividis") else cmap(np.linspace(0, 1, len(PD_Models)))
# color_map = dict(zip(PD_Models, colors))
# # Resolve hatch to one per PD model (list, single pattern, or None)
# n = len(PD_Models)
# hatch_list = [None] * n if BAR_HATCH is None else (list(BAR_HATCH) + [None] * n)[:n] if isinstance(BAR_HATCH, (list, tuple)) else [BAR_HATCH] * n
# handles_legend = None  # collect from first subplot for shared legend

# for ax, dataset in zip(axes, DATASETS):
#     df = datasets_dfs[dataset]
#     df_plot = df.xs(METRIC, axis=1, level=1)
#     df_plot = df_plot.astype(float)
#     x = np.arange(len(QG_Models))
#     width = 0.8 / len(PD_Models)
#     for i, pd_model in enumerate(PD_Models):
#         offset = (i - len(PD_Models) / 2 + 0.5) * width
#         vals = df_plot[pd_model].values
#         hatch = hatch_list[i] or None
#         bars = ax.bar(x + offset, vals, width, label=pd_model, color=color_map[pd_model], edgecolor=BAR_EDGE_COLOR, linewidth=BAR_EDGE_WIDTH, alpha=BAR_ALPHA, hatch=hatch)
#         # Value labels: one decimal, vertical (rotation=90)
#         for j, (bar, v) in enumerate(zip(bars, vals)):
#             if v is not None and not (isinstance(v, float) and np.isnan(v)):
#                 ax.text(bar.get_x() + bar.get_width() / 2, bar.get_height() + 1.5, f"{float(v):.1f}",
#                         rotation=90, ha="center", va="bottom", fontsize=7, color="black")

#     if handles_legend is None:
#         handles_legend, labels_legend = ax.get_legend_handles_labels()

#     ax.set_xticks(x)
#     ax.set_xticklabels(QG_Models, rotation=25, ha="right")
#     ax.set_ylabel(METRIC)
#     ax.set_title(dataset, fontsize=12, fontweight="bold")
#     ax.set_ylim(0, 105)
#     # ax.grid(axis="y", alpha=0.3)
#     ax.spines["top"].set_visible(False)
#     ax.spines["right"].set_visible(False)

# # Single shared legend below the 2×2 grid
# fig.legend(handles_legend, labels_legend, loc="lower center", ncol=len(PD_Models), frameon=True, fontsize=9, columnspacing=1.2)

# #plt.suptitle(f"LoQA: QG model (X) × PD model (bars) — {METRIC}", fontsize=14, fontweight="bold", y=1.02)
# plt.tight_layout(rect=[0, 0.06, 1, 1])  # leave room for legend

# if SAVE_PATH:
#     fig.savefig(SAVE_PATH, dpi=SAVE_DPI, bbox_inches="tight")
#     print(f"Saved to {SAVE_PATH} at {SAVE_DPI} DPI")
# plt.show()